"use strict";

// Generated by fetch_data.py (data/data.js). Undefined if the file is missing.
const DATA = window.MACRO_DATA;

// ------------------------------------------------------------------ formatting

const numberFormats = new Map();

function formatNumber(value, decimals) {
  const digits = Math.abs(value) >= 1000 ? 0 : decimals;
  if (!numberFormats.has(digits)) {
    numberFormats.set(digits, new Intl.NumberFormat("da-DK", {
      minimumFractionDigits: digits,
      maximumFractionDigits: digits,
    }));
  }
  return numberFormats.get(digits).format(value);
}

function changeUnit(panel) {
  if (panel.change === "pct") return " %";
  // A change in a percentage (a rate, a growth rate, a spread) is measured in %-points.
  return panel.unit.includes("%") ? " %-point" : "";
}

function changeDecimals(change, panel) {
  if (panel.change !== "pct") return panel.decimals;
  return Math.abs(change) < 1 ? 2 : 1; // small moves (e.g. the pegged EUR/DKK) need two decimals
}

// Sign and arrow follow the value as displayed, so a tiny move never shows as "▼ −0,00".
function roundedChange(change, panel) {
  const decimals = changeDecimals(change, panel);
  return { value: Number(change.toFixed(decimals)), decimals };
}

function formatChange(change, panel) {
  const { value, decimals } = roundedChange(change, panel);
  const sign = value > 0 ? "+" : value < 0 ? "−" : "±";
  return `${sign}${formatNumber(Math.abs(value), decimals)}${changeUnit(panel)}`;
}

// Dates in data.js are ISO dates for the first day of the period, so format in UTC
// to avoid a time zone shifting e.g. 2026-08-01 back to July.
const MONTH_FORMAT = new Intl.DateTimeFormat("da-DK", { month: "short", year: "numeric", timeZone: "UTC" });
const DAY_FORMAT = new Intl.DateTimeFormat("da-DK", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" });

function formatPeriod(isoDate, frequency) {
  const date = new Date(`${isoDate}T00:00:00Z`);
  switch (frequency) {
    case "A": return String(date.getUTCFullYear());
    case "Q": return `${Math.floor(date.getUTCMonth() / 3) + 1}. kvt. ${date.getUTCFullYear()}`;
    case "M": return MONTH_FORMAT.format(date);
    default: return DAY_FORMAT.format(date);
  }
}

function periodLabel(series) {
  const { lastDate } = series.summary;
  const isForecast = series.forecastFrom !== null && lastDate >= series.forecastFrom;
  return formatPeriod(lastDate, series.frequency) + (isForecast ? " (prognose)" : "");
}

// --------------------------------------------------------------------- DOM helpers

// Text always goes in through textContent: labels come from external APIs.
function el(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

function seriesColor(index) {
  return `var(--series-${index + 1})`;
}

function renderChange(change, panel) {
  const cell = el("dd");
  const { value } = roundedChange(change, panel);
  if (value !== 0) {
    const arrow = el("span", "arrow", value > 0 ? "▲" : "▼");
    arrow.setAttribute("aria-hidden", "true");
    cell.append(arrow);
  }
  cell.append(formatChange(change, panel));
  return cell;
}

// ---------------------------------------------------------------------- card parts

function renderHeadline(panel) {
  const primary = panel.series[0];
  const box = el("div", "headline");
  if (!primary.summary) {
    box.append(el("p", "error-text", `⚠ Data mangler (${primary.error ?? "ukendt fejl"})`));
    return box;
  }

  const row = el("div", "headline-row");
  const meta = panel.series.length > 1 ? `${primary.label} · ${periodLabel(primary)}` : periodLabel(primary);
  row.append(el("span", "headline-value", formatNumber(primary.summary.last, panel.decimals)),
             el("span", "headline-meta", meta));

  const deltas = el("dl", "deltas");
  for (const [label, change] of [["1 md.", primary.summary.change1m], ["1 år", primary.summary.change1y]]) {
    if (change === null) continue; // e.g. quarterly data has no 1-month change
    const item = el("div", "delta");
    item.append(el("dt", "", label), renderChange(change, panel));
    deltas.append(item);
  }
  box.append(row, deltas);
  return box;
}

function renderSeriesTable(panel) {
  const table = el("table", "series-table");
  table.append(el("caption", "visually-hidden", `Seneste værdier: ${panel.title}`));

  const headRow = el("tr");
  for (const [text, className] of [["Serie", ""], ["Seneste", "num"], ["1 år", "num"], ["Periode", "num"]]) {
    headRow.append(el("th", className, text));
  }
  const head = el("thead");
  head.append(headRow);
  table.append(head);

  const body = el("tbody");
  panel.series.forEach((series, index) => {
    const row = el("tr");
    const name = el("td");
    const swatch = el("span", "swatch");
    swatch.style.setProperty("--swatch", seriesColor(index));
    swatch.setAttribute("aria-hidden", "true");
    name.append(swatch, series.label);
    row.append(name);

    if (series.summary) {
      const { last, change1y } = series.summary;
      row.append(
        el("td", "num", formatNumber(last, panel.decimals)),
        el("td", "num", change1y === null ? "–" : formatChange(change1y, panel)),
        el("td", "num period", periodLabel(series)),
      );
    } else {
      const error = el("td", "num error-text", "⚠ Data mangler");
      error.colSpan = 3;
      error.title = series.error ?? "";
      row.append(error);
    }
    body.append(row);
  });
  table.append(body);
  return table;
}

function renderCard(panel) {
  const card = el("article", "card");
  const head = el("header", "card-head");
  head.append(el("h2", "card-title", panel.title), el("span", "card-unit", panel.unit));
  card.append(head, el("p", "card-desc", panel.description), renderHeadline(panel));
  if (panel.series.length > 1) card.append(renderSeriesTable(panel));
  return card;
}

// ---------------------------------------------------------------- sections + routing

function currentSectionId() {
  const requested = location.hash.slice(1);
  return DATA.sections.some(section => section.id === requested) ? requested : DATA.sections[0].id;
}

function renderTabs(activeId) {
  const links = DATA.sections.map(section => {
    const link = el("a", "tab", section.title);
    link.href = `#${section.id}`;
    if (section.id === activeId) link.setAttribute("aria-current", "page");
    return link;
  });
  document.getElementById("tabs").replaceChildren(...links);
}

function renderSection(sectionId) {
  const panels = DATA.panels.filter(panel => panel.section === sectionId);
  document.getElementById("panels").replaceChildren(...panels.map(renderCard));
}

function route() {
  const sectionId = currentSectionId();
  renderTabs(sectionId);
  renderSection(sectionId);
}

function init() {
  if (!DATA) {
    document.getElementById("load-error").hidden = false;
    return;
  }
  window.addEventListener("hashchange", route);
  route();
}

init();
