"use strict";

// Generated by fetch_data.py (data/data.js). Undefined if the file is missing.
const DATA = window.MACRO_DATA;

// ------------------------------------------------------------------ formatting

const numberFormats = new Map();

function formatNumber(value, decimals) {
  const digits = Math.abs(value) >= 1000 ? 0 : decimals;
  if (!numberFormats.has(digits)) {
    numberFormats.set(digits, new Intl.NumberFormat("da-DK", {
      minimumFractionDigits: digits,
      maximumFractionDigits: digits,
    }));
  }
  return numberFormats.get(digits).format(value);
}

function changeUnit(panel) {
  if (panel.change === "pct") return " %";
  // A change in a percentage (a rate, a growth rate, a spread) is measured in %-points.
  return panel.unit.includes("%") ? " %-point" : "";
}

function changeDecimals(change, panel) {
  if (panel.change !== "pct") return panel.decimals;
  return Math.abs(change) < 1 ? 2 : 1; // small moves (e.g. the pegged EUR/DKK) need two decimals
}

// Sign and arrow follow the value as displayed, so a tiny move never shows as "▼ −0,00".
function roundedChange(change, panel) {
  const decimals = changeDecimals(change, panel);
  return { value: Number(change.toFixed(decimals)), decimals };
}

function formatChange(change, panel) {
  const { value, decimals } = roundedChange(change, panel);
  const sign = value > 0 ? "+" : value < 0 ? "−" : "±";
  return `${sign}${formatNumber(Math.abs(value), decimals)}${changeUnit(panel)}`;
}

// Dates in data.js are ISO dates for the first day of the period, so format in UTC
// to avoid a time zone shifting e.g. 2026-08-01 back to July.
const MONTH_FORMAT = new Intl.DateTimeFormat("da-DK", { month: "short", year: "numeric", timeZone: "UTC" });
const DAY_FORMAT = new Intl.DateTimeFormat("da-DK", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" });

function formatPeriod(isoDate, frequency) {
  const date = new Date(`${isoDate}T00:00:00Z`);
  switch (frequency) {
    case "A": return String(date.getUTCFullYear());
    case "Q": return `${Math.floor(date.getUTCMonth() / 3) + 1}. kvt. ${date.getUTCFullYear()}`;
    case "M": return MONTH_FORMAT.format(date);
    default: return DAY_FORMAT.format(date);
  }
}

function periodLabel(series) {
  const { lastDate } = series.summary;
  const isForecast = series.forecastFrom !== null && lastDate >= series.forecastFrom;
  return formatPeriod(lastDate, series.frequency) + (isForecast ? " (prognose)" : "");
}

// ---------------------------------------------------------------------- references

// A reference ({ref, label}) shows a series that another panel owns, e.g. a country's
// inflation in a regional overview. The owner's data is filled in once here, so charts,
// tables and CSV work unchanged; isReference keeps the copy out of Signals and Compare.
function resolveReferences() {
  const owned = new Map();
  for (const panel of DATA.panels) {
    for (const series of panel.series) if (!series.ref) owned.set(series.key, { series, panel });
  }
  for (const panel of DATA.panels) {
    panel.series = panel.series.map(series => {
      if (!series.ref) return series;
      const owner = owned.get(series.ref);
      if (owner) {
        // The owner's unit and change type travel along, for split cards (one chart per series).
        const { unit, change, decimals } = owner.panel;
        return { ...owner.series, label: series.label, isReference: true, unit, change, decimals };
      }
      // Only a broken catalog gets here (a test guards against it): show it as missing data.
      return {
        key: series.ref, label: series.label, source: "", sourceUrl: null, frequency: null,
        forecastFrom: null, error: "Ukendt serie", stale: false, fallbackFrom: null,
        summary: null, data: [], isReference: true,
      };
    });
  }
}

// How one series of a panel is formatted and drawn. In a split card every series has its own
// chart in its own unit; a referenced series brings its owner's unit and change type.
function seriesPanel(panel, series) {
  if (!panel.split) return panel;
  return {
    ...panel,
    title: series.label,
    unit: series.unit ?? panel.unit,
    change: series.change ?? panel.change,
    decimals: series.decimals ?? panel.decimals,
    referenceLines: [],
    series: [series],
  };
}

// Signals only count a panel where its headline series is owned, so a series shown in
// a country tab and in its region's overview appears once.
function ownsHeadline(panel) {
  return !panel.series[0].isReference;
}

// --------------------------------------------------------------------- DOM helpers

// Text always goes in through textContent: labels come from external APIs.
function el(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

function seriesColor(index) {
  return `var(--series-${index + 1})`;
}

function renderChange(change, panel) {
  const cell = el("dd");
  const { value } = roundedChange(change, panel);
  if (value !== 0) {
    const arrow = el("span", "arrow", value > 0 ? "▲" : "▼");
    arrow.setAttribute("aria-hidden", "true");
    cell.append(arrow);
  }
  cell.append(formatChange(change, panel));
  return cell;
}

// ---------------------------------------------------------------------- card parts

function renderHeadline(panel) {
  const primary = panel.series[0];
  const box = el("div", "headline");
  if (!primary.summary) {
    box.append(el("p", "error-text", `⚠ Data mangler (${primary.error ?? "ukendt fejl"})`));
    return box;
  }

  const row = el("div", "headline-row");
  const meta = panel.series.length > 1 ? `${primary.label} · ${periodLabel(primary)}` : periodLabel(primary);
  row.append(el("span", "headline-value", formatNumber(primary.summary.last, panel.decimals)),
             el("span", "headline-meta", meta));

  const deltas = el("dl", "deltas");
  for (const [label, change] of [["1 md.", primary.summary.change1m], ["1 år", primary.summary.change1y]]) {
    if (change === null) continue; // e.g. quarterly data has no 1-month change
    const item = el("div", "delta");
    item.append(el("dt", "", label), renderChange(change, panel));
    deltas.append(item);
  }
  const percentile = primary.summary.percentile10y; // undefined in data files from before this feature
  if (percentile !== null && percentile !== undefined) {
    const rank = Math.round(percentile);
    const item = el("div", "delta");
    const value = el("dd", "", `${rank}. percentil`);
    value.title = `Højere end ca. ${rank} % af målingerne de seneste 10 år`;
    item.append(el("dt", "", "Niveau, 10 år"), value);
    deltas.append(item);
  }
  box.append(row, deltas);
  return box;
}

function renderSeriesTable(panel) {
  const table = el("table", "series-table");
  table.append(el("caption", "visually-hidden", `Seneste værdier: ${panel.title}`));

  const headRow = el("tr");
  for (const [text, className] of [["Serie", ""], ["Seneste", "num"], ["1 år", "num"], ["Periode", "num period"]]) {
    headRow.append(el("th", className, text));
  }
  const head = el("thead");
  head.append(headRow);
  table.append(head);

  const body = el("tbody");
  panel.series.forEach((series, index) => {
    const row = el("tr");
    const swatch = el("span", "swatch");
    swatch.style.setProperty("--swatch", seriesColor(index));
    swatch.setAttribute("aria-hidden", "true");
    const nameText = el("div", "", series.label);
    const name = el("div", "series-name");
    name.append(swatch, nameText);
    const nameCell = el("td");
    nameCell.append(name);
    row.append(nameCell);

    if (series.summary) {
      const { last, change1y } = series.summary;
      const note = freshnessNote(series);
      const periodText = (note ? "⚠ " : "") + periodLabel(series);
      // On narrow screens the period column is hidden and this copy under the name shows instead.
      nameText.append(el("span", "period-inline", periodText));
      const period = el("td", "num period", periodText);
      if (note) period.title = note;
      const format = seriesPanel(panel, series);
      row.append(
        el("td", "num", formatNumber(last, format.decimals)),
        el("td", "num", change1y === null ? "–" : formatChange(change1y, format)),
        period,
      );
    } else {
      const error = el("td", "num error-text", "⚠ Data mangler");
      error.colSpan = 3;
      error.title = series.error ?? "";
      row.append(error);
    }
    body.append(row);
  });
  table.append(body);
  return table;
}

// ------------------------------------------------------------ freshness + sources

const FETCH_TIME_FORMAT = new Intl.DateTimeFormat("da-DK", {
  day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit",
});
const FETCH_DATE_FORMAT = new Intl.DateTimeFormat("da-DK", { day: "numeric", month: "short", year: "numeric" });
const FREQUENCY_ADJECTIVES = { D: "daglige", W: "ugentlige", M: "månedlige", Q: "kvartalsvise", A: "årlige" };
const OLD_DATA_DAYS = 2; // the update job runs daily, so older data means it has stopped

function renderUpdated() {
  const fetchedAt = new Date(DATA.generatedAt);
  const ageDays = Math.floor((Date.now() - fetchedAt.getTime()) / 86_400_000);
  const node = document.getElementById("updated");
  const text = `Data hentet ${FETCH_TIME_FORMAT.format(fetchedAt)}`;
  if (ageDays >= OLD_DATA_DAYS) {
    node.textContent = `⚠ ${text} (${ageDays} dage siden – den daglige opdatering kører måske ikke)`;
    node.classList.add("is-old");
  } else {
    node.textContent = text;
  }
}

// Why a series' latest value might not be current, or null if it is.
function freshnessNote(series) {
  if (series.fallbackFrom) {
    return `Seneste hentning fejlede – viser data hentet ${FETCH_DATE_FORMAT.format(new Date(series.fallbackFrom))}`;
  }
  if (series.stale) {
    return `Forældet: nyeste tal er ældre end normalt for ${FREQUENCY_ADJECTIVES[series.frequency]} data`;
  }
  return null;
}

function renderNotes(panel) {
  const labelsByNote = new Map();
  for (const series of panel.series) {
    const note = freshnessNote(series);
    if (note === null) continue;
    if (!labelsByNote.has(note)) labelsByNote.set(note, []);
    labelsByNote.get(note).push(series.label);
  }
  if (labelsByNote.size === 0) return null;

  const list = el("ul", "notes");
  for (const [note, labels] of labelsByNote) {
    // A note that applies to every series in the card is said once, without naming them.
    const prefix = labels.length === panel.series.length ? "" : `${labels.join(", ")}: `;
    list.append(el("li", "", `⚠ ${prefix}${note}`));
  }
  return list;
}

function sourceLink(text, url) {
  if (!url) return text; // derived series are computed here, so there is nothing to link to
  const link = el("a", "", text);
  link.href = url;
  link.target = "_blank";
  link.rel = "noopener noreferrer";
  return link;
}

// "Kilde: FRED · Danmarks Statistik: Huse, Lejligheder" – one link per distinct page.
function renderSources(panel) {
  const seriesBySource = new Map();
  for (const series of panel.series) {
    if (!seriesBySource.has(series.source)) seriesBySource.set(series.source, []);
    seriesBySource.get(series.source).push(series);
  }

  const footer = el("p", "card-sources", "Kilde: ");
  [...seriesBySource].forEach(([source, members], groupIndex) => {
    if (groupIndex > 0) footer.append(" · ");
    const distinctUrls = new Set(members.map(series => series.sourceUrl));
    if (distinctUrls.size === 1) {
      footer.append(sourceLink(source, members[0].sourceUrl));
      return;
    }
    footer.append(`${source}: `);
    members.forEach((series, index) => {
      if (index > 0) footer.append(", ");
      footer.append(sourceLink(series.label, series.sourceUrl));
    });
  });
  return footer;
}

// ------------------------------------------------------------------------- CSV export

function csvField(text) {
  return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

// Long format (one row per observation), because the series of a panel can have
// different dates, e.g. daily and monthly gas prices.
function panelCsv(panel) {
  const rows = ["dato,serie,værdi"];
  for (const series of panel.series) {
    for (const [date, value] of series.data) rows.push(`${date},${csvField(series.label)},${value}`);
  }
  return rows.join("\n") + "\n";
}

function downloadCsv(panel) {
  // The BOM tells Excel the file is UTF-8, so æ, ø and å display correctly.
  const blob = new Blob(["﻿" + panelCsv(panel)], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = el("a");
  link.href = url;
  link.download = `${panel.id}.csv`;
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000); // give the browser time to start the download
}

function renderCsvButton(panel) {
  const button = el("button", "csv-button", "CSV");
  button.type = "button";
  button.title = "Download data som CSV. Dagsdata ældre end 2 år er tyndet ud til ét punkt pr. uge.";
  button.setAttribute("aria-label", `Download ${panel.title} som CSV`);
  button.addEventListener("click", () => downloadCsv(panel));
  return button;
}

function renderCard(panel) {
  const card = el("article", "card");
  card.id = `panel-${panel.id}`; // target for the links on the Signals tab
  const head = el("header", "card-head");
  head.append(el("h3", "card-title", panel.title), el("span", "card-unit", panel.unit));
  card.append(head, el("p", "card-desc", panel.description), renderHeadline(panel));
  if (panel.series.some(series => series.data.length > 0)) {
    card.append(panel.split ? renderSplitCharts(panel) : renderChartSlot(panel));
  }
  if (panel.series.length > 1) card.append(renderSeriesTable(panel));
  const notes = renderNotes(panel);
  if (notes) card.append(notes);
  const footer = el("div", "card-footer");
  footer.append(renderSources(panel));
  if (panel.series.some(series => series.data.length > 0)) footer.append(renderCsvButton(panel));
  card.append(footer);
  return card;
}

// -------------------------------------------------------------------------- charts

let rangeYears = DEFAULT_RANGE_YEARS; // 0 = all data; the default comes from lib.js
let activeCharts = [];

const AXIS_NUMBER_FORMAT = new Intl.NumberFormat("da-DK", { maximumFractionDigits: 2 });
// Local time on purpose: the date adapter places ticks at local midnight, so in UTC
// "1 Jan 2022 00:00" in Copenhagen would still be 2021.
const AXIS_MONTH_FORMAT = new Intl.DateTimeFormat("da-DK", { month: "short", year: "2-digit" });

function cssVar(name) {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
}

function isoDate(timestamp) {
  return new Date(timestamp).toISOString().slice(0, 10);
}

function rangeStart(years) {
  if (years === 0) return undefined;
  // Counted back from when the data was fetched, so an old data file still shows its data.
  const start = new Date(DATA.generatedAt);
  start.setUTCFullYear(start.getUTCFullYear() - years);
  return start.getTime();
}

function timeUnit(years) {
  return years === 1 ? "month" : "year";
}

function formatAxisDate(timestamp) {
  const date = new Date(timestamp);
  return rangeYears === 1 ? AXIS_MONTH_FORMAT.format(date) : String(date.getFullYear());
}

// Binary search for the point closest to pixel x; points are sorted by date.
function nearestIndex(points, x) {
  let low = 0;
  let high = points.length - 1;
  while (low < high) {
    const middle = (low + high) >> 1;
    if (points[middle].x < x) low = middle + 1;
    else high = middle;
  }
  const previousIsCloser = low > 0 && x - points[low - 1].x < points[low].x - x;
  return previousIsCloser ? low - 1 : low;
}

// Hover mode: the point closest to the pointer in *each* series. Chart.js' built-in
// "index" mode assumes all series share the same dates, which mixed daily/monthly
// series and rates from different central banks don't.
function nearestPerSeries(chart, event) {
  const { left, right } = chart.chartArea;
  const items = [];
  chart.data.datasets.forEach((dataset, datasetIndex) => {
    const points = chart.getDatasetMeta(datasetIndex).data;
    if (points.length === 0) return;
    const index = nearestIndex(points, event.x);
    const point = points[index];
    if (point.x >= left && point.x <= right) items.push({ element: point, datasetIndex, index });
  });
  return items;
}

// A vertical hairline at the hovered date.
const crosshairPlugin = {
  id: "crosshair",
  afterDatasetsDraw(chart) {
    const active = chart.tooltip?.getActiveElements() ?? [];
    if (active.length === 0) return;
    const x = active[0].element.x;
    const { ctx, chartArea } = chart;
    ctx.save();
    ctx.strokeStyle = cssVar("--baseline");
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(x, chartArea.top);
    ctx.lineTo(x, chartArea.bottom);
    ctx.stroke();
    ctx.restore();
  },
};

// Grey bands behind the lines for recessions, so turning points read in context.
const recessionPlugin = {
  id: "recessions",
  beforeDatasetsDraw(chart, args, options) {
    const periods = options.periods ?? [];
    if (periods.length === 0) return;
    const { ctx, chartArea, scales } = chart;
    ctx.save();
    ctx.fillStyle = cssVar("--recession");
    for (const [start, end] of periods) {
      const left = Math.max(scales.x.getPixelForValue(start), chartArea.left);
      const right = Math.min(scales.x.getPixelForValue(end), chartArea.right);
      if (right > left) ctx.fillRect(left, chartArea.top, right - left, chartArea.bottom - chartArea.top);
    }
    ctx.restore();
  },
};

const RECESSION_NOTES = {
  us: "Grå felter: recessioner i USA (NBER).",
  euro_area: "Grå felter: recessioner i eurozonen (CEPR).",
};

function recessionPeriods(sectionId) {
  const source = DATA.sections.find(section => section.id === sectionId)?.recessions;
  const periods = (source && DATA.recessions?.[source]) ?? [];
  return periods.map(([start, end]) => [Date.parse(start), Date.parse(end)]);
}

// Dashed horizontal lines for targets and thresholds (e.g. a 2 % inflation target).
// Dashed on purpose, so they read as a threshold and not as one more gridline.
const referenceLinesPlugin = {
  id: "referenceLines",
  beforeDatasetsDraw(chart, args, options) {
    const lines = options.lines ?? [];
    if (lines.length === 0) return;
    const { ctx, chartArea, scales } = chart;
    ctx.save();
    ctx.strokeStyle = cssVar("--text-muted");
    ctx.fillStyle = cssVar("--text-muted");
    ctx.lineWidth = 1;
    ctx.setLineDash([4, 4]);
    ctx.font = "11px system-ui, -apple-system, sans-serif";
    ctx.textAlign = "right";
    ctx.textBaseline = "bottom";
    for (const { value, label } of lines) {
      const y = scales.y.getPixelForValue(value);
      if (y < chartArea.top || y > chartArea.bottom) continue;
      ctx.beginPath();
      ctx.moveTo(chartArea.left, y);
      ctx.lineTo(chartArea.right, y);
      ctx.stroke();
      ctx.fillText(label, chartArea.right - 2, y - 2);
    }
    ctx.restore();
  },
};

function tooltipPeriod(item) {
  const date = isoDate(item.parsed.x);
  const { frequency, forecastFrom } = item.dataset;
  const isForecast = forecastFrom !== null && date >= forecastFrom;
  return formatPeriod(date, frequency) + (isForecast ? " (prognose)" : "");
}

function tooltipOptions(panel) {
  return {
    backgroundColor: cssVar("--surface"),
    borderColor: cssVar("--border"),
    borderWidth: 1,
    titleColor: cssVar("--text-secondary"),
    titleFont: { weight: "normal" },
    bodyColor: cssVar("--text-primary"),
    padding: 8,
    usePointStyle: true,
    callbacks: {
      title: items => tooltipPeriod(items[0]),
      // A regular function: Chart.js passes the tooltip as `this`, which holds all rows.
      label(item) {
        const value = formatNumber(item.parsed.y, panel.decimals);
        const period = tooltipPeriod(item);
        const ownDate = period === tooltipPeriod(this.dataPoints[0]) ? "" : ` (${period})`;
        return panel.series.length > 1 ? `${value}  ${item.dataset.label}${ownDate}` : value + ownDate;
      },
      labelPointStyle: () => ({ pointStyle: "line", rotation: 0 }),
    },
  };
}

function buildDatasets(panel) {
  const surface = cssVar("--surface");
  return panel.series.map((series, index) => {
    // A split card's charts continue the card's colour order, matching its series table.
    const color = cssVar(`--series-${index + 1 + (panel.colorOffset ?? 0)}`);
    const forecastStart = series.forecastFrom ? Date.parse(series.forecastFrom) : null;
    return {
      label: series.label,
      frequency: series.frequency, // our own fields, read by the tooltip
      forecastFrom: series.forecastFrom,
      data: series.data.map(([date, value]) => ({ x: Date.parse(date), y: value })),
      borderColor: color,
      backgroundColor: color,
      borderWidth: 2,
      pointRadius: 0,
      pointHoverRadius: 4,
      pointHoverBorderWidth: 2,
      pointHoverBorderColor: surface,
      // Forecast years are dashed, so a projection never passes for data.
      segment: forecastStart === null ? undefined : {
        borderDash: context => (context.p1.parsed.x >= forecastStart ? [4, 4] : undefined),
      },
    };
  });
}

function chartOptions(panel) {
  const gridColor = cssVar("--gridline");
  const zeroLineColor = cssVar("--baseline");
  const tickColor = cssVar("--text-muted");
  const referenceLines = panel.referenceLines ?? []; // missing in data files from before this feature
  const referenceValues = referenceLines.map(line => line.value);
  return {
    animation: false,
    maintainAspectRatio: false,
    parsing: false, // data is already {x, y} ...
    normalized: true, // ... and sorted by date, so Chart.js can skip that work
    interaction: { mode: "nearestPerSeries", intersect: false },
    plugins: {
      legend: { display: false },
      tooltip: tooltipOptions(panel),
      referenceLines: { lines: referenceLines },
      recessions: { periods: recessionPeriods(panel.section) },
    },
    scales: {
      x: {
        type: "time",
        min: rangeStart(rangeYears),
        max: panel.xMax, // a split card's charts end on the same date, so they line up
        time: { unit: timeUnit(rangeYears) },
        grid: { display: false },
        border: { color: zeroLineColor },
        ticks: { color: tickColor, maxRotation: 0, maxTicksLimit: 6, callback: formatAxisDate },
      },
      y: {
        // Stretch the axis so every reference line stays visible, e.g. a 2 % target
        // when inflation has been above 3 % for the whole period.
        suggestedMin: referenceValues.length ? Math.min(...referenceValues) : undefined,
        suggestedMax: referenceValues.length ? Math.max(...referenceValues) : undefined,
        border: { display: false },
        // A stronger line at zero: crossing it matters for spreads, growth and job gains.
        grid: { color: context => (context.tick.value === 0 ? zeroLineColor : gridColor) },
        // 6, not 5: with 5, a value just below zero (Japan's −0.1 %) needs one extra step,
        // so Chart.js jumps to a coarser step and leaves half the axis empty.
        ticks: { color: tickColor, maxTicksLimit: 6, callback: value => AXIS_NUMBER_FORMAT.format(value) },
      },
    },
  };
}

function renderChartSlot(panel, className = "chart") {
  const slot = el("div", className);
  const canvas = el("canvas");
  canvas.setAttribute("role", "img");
  canvas.setAttribute("aria-label", `Graf: ${panel.title}`);
  canvas.chartPanel = panel; // what to draw, read when the chart is created
  slot.append(canvas);
  return slot;
}

// One small chart per series, stacked on a shared time axis: series in different units
// (a ratio and a rate, a price and an exchange rate) never share a y-axis.
function renderSplitCharts(panel) {
  const box = el("div", "split-charts");
  const latest = Math.max(...panel.series.filter(series => series.data.length)
    .map(series => Date.parse(series.data.at(-1)[0])));
  panel.series.forEach((series, index) => {
    if (series.data.length === 0) return;
    const part = { ...seriesPanel(panel, series), xMax: latest, colorOffset: index };
    const label = el("p", "split-label", part.unit ? `${series.label} (${part.unit})` : series.label);
    box.append(label, renderChartSlot(part, "chart chart-split"));
  });
  return box;
}

function createChart(canvas, panel) {
  return new Chart(canvas, { type: "line", data: { datasets: buildDatasets(panel) }, options: chartOptions(panel) });
}

function destroyCharts() {
  for (const chart of activeCharts) chart.destroy(); // frees the canvases of the previous tab
  activeCharts = [];
}

function updateRangeButtons() {
  for (const button of document.querySelectorAll("#range-picker button")) {
    button.setAttribute("aria-pressed", String(Number(button.dataset.years) === rangeYears));
  }
}

// ---------------------------------------------------------------------- signals tab

const SIGNALS_TAB = { id: "signals", title: "Signaler" };
const MOVERS_SHOWN = 8;
const HEAT_LEGEND = [
  ["neg-strong", "Meget lavt"], ["neg-weak", "Lavt"], ["neutral", "Normalt"],
  ["pos-weak", "Højt"], ["pos-strong", "Meget højt"], ["none", "Ingen 10-års historik"],
];
let scrollTargetPanelId = null; // set when a signal is clicked, used after the section renders
let shownSectionId = null; // the tab currently on screen

// The z-score bins of the heat scale: |z| < 0.5 is normal, beyond 1.5 is unusual.
function heatLevel(z) {
  if (z === null || z === undefined) return "none";
  if (z <= -1.5) return "neg-strong";
  if (z <= -0.5) return "neg-weak";
  if (z < 0.5) return "neutral";
  if (z < 1.5) return "pos-weak";
  return "pos-strong";
}

function formatSigned(value, decimals) {
  const rounded = Number(value.toFixed(decimals));
  const sign = rounded > 0 ? "+" : rounded < 0 ? "−" : "±";
  return sign + formatNumber(Math.abs(rounded), decimals);
}

function panelName(panel) {
  return panel.series.length > 1 ? `${panel.title}: ${panel.series[0].label}` : panel.title;
}

function sectionTitle(sectionId) {
  return DATA.sections.find(section => section.id === sectionId)?.title ?? "";
}

function goToPanel(panel) {
  scrollTargetPanelId = panel.id;
  location.hash = hashFor(panel.section, rangeYears);
}

function renderMovers() {
  const movers = DATA.panels
    .filter(panel => ownsHeadline(panel) && typeof panel.series[0].summary?.weekMoveZ === "number")
    .sort((a, b) => Math.abs(b.series[0].summary.weekMoveZ) - Math.abs(a.series[0].summary.weekMoveZ))
    .slice(0, MOVERS_SHOWN);
  const list = el("ol", "movers");
  for (const panel of movers) {
    const { weekChange, weekMoveZ } = panel.series[0].summary;
    const button = el("button", "mover");
    button.type = "button";
    button.append(
      el("span", "mover-name", panelName(panel)),
      el("span", "mover-section", sectionTitle(panel.section)),
      el("span", "mover-change", formatChange(weekChange, panel)),
      el("span", "mover-size", `${formatNumber(Math.abs(weekMoveZ), 1)} × en typisk uge`),
    );
    button.addEventListener("click", () => goToPanel(panel));
    const item = el("li");
    item.append(button);
    list.append(item);
  }
  return list;
}

function renderHeatTile(panel) {
  const summary = panel.series[0].summary;
  const z = summary?.zscore10y;
  const tile = el("button", `heat-tile heat-${heatLevel(z)}`);
  tile.type = "button";
  tile.append(el("span", "heat-title", panelName(panel)));
  if (summary) tile.append(el("span", "heat-value", formatNumber(summary.last, panel.decimals)));
  const zText = typeof z === "number" ? `z ${formatSigned(z, 1)}` : "ingen 10-års historik";
  tile.append(el("span", "heat-z", zText));
  tile.title = typeof z === "number"
    ? `${formatSigned(z, 1)} standardafvigelser fra gennemsnittet de seneste 10 år`
    : "Serien er for ung eller for sjælden til at sammenligne med 10 år";
  tile.addEventListener("click", () => goToPanel(panel));
  return tile;
}

// The tiles of one section, or null if it owns no headline series (an overview that only
// refers to its countries' series).
function heatBlock(section, heading) {
  const tiles = DATA.panels.filter(panel => panel.section === section.id && ownsHeadline(panel))
    .map(renderHeatTile);
  if (tiles.length === 0) return null;
  const block = el("div", "heat-section");
  if (heading) block.append(el("h4", "heat-section-title", heading));
  const grid = el("div", "heat-grid");
  grid.append(...tiles);
  block.append(grid);
  return block;
}

// One block per region (and for Global), with a sub-heading per country.
function renderHeatmap() {
  const heatmap = el("div", "heatmap");
  for (const { section, countries } of sectionTree()) {
    const blocks = [
      heatBlock(section, countries.length ? "Oversigt" : null),
      ...countries.map(country => heatBlock(country, country.title)),
    ].filter(Boolean);
    if (blocks.length === 0) continue;
    const region = el("section", "heat-region");
    region.append(el("h3", "heat-region-title", section.title), ...blocks);
    heatmap.append(region);
  }
  return heatmap;
}

function renderHeatLegend() {
  const legend = el("div", "heat-legend");
  for (const [level, label] of HEAT_LEGEND) {
    const item = el("span", "heat-legend-item");
    const swatch = el("span", `heat-swatch heat-${level}`);
    swatch.setAttribute("aria-hidden", "true");
    item.append(swatch, label);
    legend.append(item);
  }
  return legend;
}

const EVENTS_SHOWN = 8;
const EVENT_DATE_FORMAT = new Intl.DateTimeFormat("da-DK", {
  weekday: "short", day: "numeric", month: "short", timeZone: "UTC",
});

function todayIso() {
  return new Date().toLocaleDateString("sv-SE"); // Swedish locale formats dates as YYYY-MM-DD
}

function daysUntilText(isoDate) {
  const days = Math.round((Date.parse(isoDate) - Date.parse(todayIso())) / 86_400_000);
  return days === 0 ? "i dag" : days === 1 ? "i morgen" : `om ${days} dage`;
}

function renderEvents() {
  const nodes = [el("h2", "group-heading", "Kommende begivenheder")];
  for (const warning of DATA.calendarWarnings ?? []) nodes.push(el("p", "section-note", `⚠ ${warning}`));
  // data.js may be a few days old, so drop events that have passed since it was made.
  const upcoming = (DATA.events ?? []).filter(event => event.date >= todayIso()).slice(0, EVENTS_SHOWN);
  const list = el("ul", "events");
  for (const event of upcoming) {
    const item = el("li", "event");
    item.append(
      el("span", "event-date", EVENT_DATE_FORMAT.format(new Date(Date.parse(event.date)))),
      el("span", "event-institution", event.institution),
      el("span", "event-title", event.title),
      el("span", "event-until", daysUntilText(event.date)),
    );
    list.append(item);
  }
  nodes.push(upcoming.length ? list : el("p", "section-note", "Ingen kommende begivenheder i kalenderen."));
  return nodes;
}

function renderSignals() {
  destroyCharts();
  document.getElementById("panels").replaceChildren(
    ...renderEvents(),
    el("h2", "group-heading", "Største bevægelser denne uge"),
    el("p", "section-note",
       "Ændringen over 7 dage målt mod en typisk uge de seneste 10 år. Kun serier med dags- eller ugedata."),
    renderMovers(),
    el("h2", "group-heading", "Niveau i forhold til de seneste 10 år"),
    el("p", "section-note",
       "Farven viser, hvor usædvanligt niveauet er (z-score), ikke om det er godt eller skidt. "
       + "Normalt: inden for ±0,5 standardafvigelser. Meget: over 1,5. Klik for at se grafen."),
    renderHeatLegend(),
    renderHeatmap(),
  );
}

// ---------------------------------------------------------------------- compare tab
// Two series side by side, never on two y-axes: a second y-scale can be stretched to make
// any two lines look related. Same unit -> one axis. Different units -> two charts with a
// shared time axis. Index mode rebases both to 100 at a common start date.

const COMPARE_TAB = { id: "compare", title: "Sammenlign" };
const DEFAULT_COMPARISON = { a: "de_10y", b: "us_10y" }; // German Bund vs US Treasury

function seriesLookup() {
  const lookup = new Map();
  for (const panel of DATA.panels) {
    for (const series of panel.series) {
      // A reference is listed where it is owned, so no series appears twice.
      if (series.data.length > 0 && !series.isReference) lookup.set(series.key, { panel, series });
    }
  }
  return lookup;
}

function entryName({ panel, series }) {
  return panel.series.length > 1 ? `${panel.title}: ${series.label}` : panel.title;
}

function visiblePoints(series) {
  const start = rangeStart(rangeYears) ?? -Infinity;
  return series.data.filter(([date]) => Date.parse(date) >= start);
}

// Rebasing to 100 only means something for values that are positive throughout.
function canIndex(entry) {
  const points = visiblePoints(entry.series);
  return points.length > 0 && points.every(([, value]) => value > 0);
}

function rebaseToCommonStart(entries) {
  const commonStart = entries.map(entry => visiblePoints(entry.series)[0][0]).sort().at(-1);
  const series = entries.map(entry => {
    const points = entry.series.data.filter(([date]) => date >= commonStart);
    const base = points[0][1];
    return { ...entry.series, label: entryName(entry), data: points.map(([date, value]) => [date, value / base * 100]) };
  });
  return { commonStart, series };
}

function comparePanel(title, unit, decimals, series) {
  return { id: "compare", section: COMPARE_TAB.id, title, unit, decimals, change: "diff", referenceLines: [], series };
}

function renderSeriesSelect(label, selectedKey, lookup, onChange) {
  const field = el("label", "compare-field");
  const select = el("select");
  // Grouped like the menu: "Europa", "Europa · Tyskland", ... Overviews that only refer to
  // their countries' series have nothing of their own to list.
  for (const { section, countries } of sectionTree()) {
    for (const member of [section, ...countries]) {
      const entries = [...lookup].filter(([, entry]) => entry.panel.section === member.id);
      if (entries.length === 0) continue;
      const group = el("optgroup");
      group.label = member === section ? section.title : `${section.title} · ${member.title}`;
      for (const [key, entry] of entries) {
        const option = el("option", "", entryName(entry));
        option.value = key;
        option.selected = key === selectedKey;
        group.append(option);
      }
      select.append(group);
    }
  }
  select.addEventListener("change", () => onChange(select.value));
  field.append(el("span", "compare-label", label), select);
  return field;
}

function renderCompareLegend(series) {
  const legend = el("div", "compare-legend");
  series.forEach((item, index) => {
    const entry = el("span", "compare-legend-item");
    const swatch = el("span", "swatch");
    swatch.style.setProperty("--swatch", seriesColor(index));
    swatch.setAttribute("aria-hidden", "true");
    entry.append(swatch, item.label);
    legend.append(entry);
  });
  return legend;
}

// Returns the cards to show plus the panels to draw, as {card, panel} pairs.
function comparisonCharts(entries, useIndex) {
  const [a, b] = entries;
  const decimals = Math.max(a.panel.decimals, b.panel.decimals);
  const chartCard = (panel, legend) => {
    const card = el("article", "card compare-card");
    card.append(el("h3", "card-title", panel.title));
    if (legend) card.append(legend);
    card.append(renderChartSlot(panel));
    return { card, panel };
  };

  if (useIndex) {
    const { commonStart, series } = rebaseToCommonStart(entries);
    const panel = comparePanel(`Indeks: begge = 100 den ${formatPeriod(commonStart, "D")}`, "Indeks", 1, series);
    return [chartCard(panel, renderCompareLegend(series))];
  }
  const named = entries.map(entry => ({ ...entry.series, label: entryName(entry) }));
  if (a.panel.unit === b.panel.unit) {
    const panel = comparePanel(`Samme enhed (${a.panel.unit}): én akse`, a.panel.unit, decimals, named);
    return [chartCard(panel, renderCompareLegend(named))];
  }
  return entries.map((entry, index) =>
    chartCard(comparePanel(`${named[index].label} (${entry.panel.unit})`, entry.panel.unit,
                           entry.panel.decimals, [named[index]])));
}

function renderCompare(params) {
  destroyCharts();
  const lookup = seriesLookup();
  const pick = (name) => (lookup.has(params.get(name)) ? params.get(name) : DEFAULT_COMPARISON[name]);
  const choice = { a: pick("a"), b: pick("b"), index: params.get("index") === "1" ? "1" : "0" };
  const entries = [lookup.get(choice.a), lookup.get(choice.b)];
  const indexPossible = entries.every(canIndex);
  const useIndex = choice.index === "1" && indexPossible;
  const update = change => {
    location.hash = hashFor(COMPARE_TAB.id, rangeYears, { ...choice, ...change });
  };

  const indexToggle = el("label", "compare-toggle");
  const checkbox = el("input");
  checkbox.type = "checkbox";
  checkbox.checked = useIndex;
  checkbox.disabled = !indexPossible;
  checkbox.addEventListener("change", () => update({ index: checkbox.checked ? "1" : "0" }));
  indexToggle.append(checkbox, "Indeks (start = 100)");

  const controls = el("div", "compare-controls");
  controls.append(
    renderSeriesSelect("Serie A", choice.a, lookup, key => update({ a: key })),
    renderSeriesSelect("Serie B", choice.b, lookup, key => update({ b: key })),
    indexToggle,
  );

  const notes = [];
  if (entries[0].panel.unit !== entries[1].panel.unit && !useIndex) {
    notes.push("Forskellige enheder: vist som to grafer med fælles tidsakse, aldrig med to y-akser.");
  }
  if (!indexPossible) {
    const notPositive = entries.filter(entry => !canIndex(entry)).map(entryName);
    notes.push(`Indeks er ikke muligt: ${notPositive.join(" og ")} har værdier på nul eller derunder i perioden.`);
  }
  const charts = comparisonCharts(entries, useIndex);

  document.getElementById("panels").replaceChildren(
    el("h2", "group-heading", "Sammenlign to serier"),
    controls,
    ...notes.map(note => el("p", "section-note", note)),
    ...charts.map(chart => chart.card),
  );

  if (typeof Chart === "undefined") return;
  const created = charts.map(({ card, panel }) => createChart(card.querySelector("canvas"), panel));
  // Two stacked charts share one time axis, so their dates line up vertically.
  const latest = Math.max(...entries.map(entry => Date.parse(entry.series.data.at(-1)[0])));
  for (const chart of created) {
    chart.options.scales.x.max = latest;
    chart.update();
  }
  activeCharts.push(...created);
}

// ---------------------------------------------------------------- sections + routing

// The URL is the single source of truth for what is shown: "#europe?range=10" means the
// Europe tab with 10 years of history. Parsing and building it are pure functions in lib.js
// (parseHashState, buildHash), tested in tests/js.

// The Signals overview is a tab of the page only; the data sections come from data.js.
function allTabs() {
  return [SIGNALS_TAB, ...DATA.sections, COMPARE_TAB];
}

function parseHash() {
  return parseHashState(location.hash, allTabs().map(tab => tab.id), SIGNALS_TAB.id);
}

function hashFor(sectionId, years, extra = {}) {
  return buildHash(sectionId, years, extra);
}

// Top-level sections in menu order, each with its countries (none for Global). Data files
// from before the regions have no region field, so every section is then top-level.
function sectionTree() {
  return DATA.sections
    .filter(section => !section.region)
    .map(section => ({ section, countries: DATA.sections.filter(child => child.region === section.id) }));
}

function tabItem(tab, activeId) {
  const item = el("li");
  const link = el("a", "tab", tab.title);
  link.href = hashFor(tab.id, rangeYears); // switching tab keeps the chosen period
  if (tab.id === activeId) link.setAttribute("aria-current", "page");
  item.append(link);
  return item;
}

function setRegionOpen(item, open) {
  item.dataset.open = String(open);
  item.querySelector(".tab").setAttribute("aria-expanded", String(open));
  // inert at once, so Tab skips a closed menu even while it is still fading out.
  item.querySelector(".region-menu").inert = !open;
}

// A region tab: a click opens the overview; hovering (mouse) or focusing (keyboard) slides
// out its countries. Touch has no hover, so it relies on the country row instead.
function regionItem(region, countries, activeId) {
  const item = el("li", "tab-region");
  const link = el("a", "tab", region.title);
  link.href = hashFor(region.id, rangeYears);
  link.setAttribute("aria-controls", `menu-${region.id}`);
  const chevron = el("span", "chevron");
  chevron.setAttribute("aria-hidden", "true");
  link.append(chevron);
  if (region.id === activeId) link.setAttribute("aria-current", "page");
  if (countries.some(country => country.id === activeId)) link.classList.add("is-active");

  const menu = el("ul", "region-menu");
  menu.id = `menu-${region.id}`;
  for (const country of countries) {
    const entry = el("li");
    const countryLink = el("a", "", country.title);
    countryLink.href = hashFor(country.id, rangeYears);
    if (country.id === activeId) countryLink.setAttribute("aria-current", "page");
    entry.append(countryLink);
    menu.append(entry);
  }
  item.append(link, menu);
  setRegionOpen(item, false);

  let closingWithEscape = false; // moving focus back to the tab must not reopen the menu
  item.addEventListener("pointerenter", event => {
    if (event.pointerType === "mouse") setRegionOpen(item, true);
  });
  item.addEventListener("pointerleave", event => {
    if (event.pointerType === "mouse" && !item.contains(document.activeElement)) setRegionOpen(item, false);
  });
  item.addEventListener("focusin", () => {
    if (!closingWithEscape) setRegionOpen(item, true);
  });
  item.addEventListener("focusout", event => {
    if (!item.contains(event.relatedTarget)) setRegionOpen(item, false);
  });
  item.addEventListener("keydown", event => {
    if (event.key !== "Escape" || item.dataset.open !== "true") return;
    closingWithEscape = true;
    link.focus();
    closingWithEscape = false;
    setRegionOpen(item, false);
  });
  return item;
}

let shownRegionId = null; // the region whose country row is on screen

// The countries of the active region as a row under the tabs. It is the way in on touch
// screens and phones, where nothing can be hovered.
function renderCountryRow(regionId, activeId) {
  const row = document.getElementById("subtabs");
  const region = sectionTree().find(node => node.section.id === regionId && node.countries.length);
  if (!region) {
    row.hidden = true;
    row.replaceChildren();
    shownRegionId = null;
    return;
  }
  const entries = [{ id: region.section.id, title: "Oversigt" }, ...region.countries];
  row.replaceChildren(...entries.map(section => {
    const link = el("a", "subtab", section.title);
    link.href = hashFor(section.id, rangeYears);
    if (section.id === activeId) link.setAttribute("aria-current", "page");
    return link;
  }));
  row.setAttribute("aria-label", `Lande i ${region.section.title}`);
  row.hidden = false;
  if (regionId !== shownRegionId) { // slide in when the region changes, not on every country
    row.classList.remove("is-entering");
    void row.offsetWidth; // restart the animation
    row.classList.add("is-entering");
  }
  shownRegionId = regionId;
}

// The tabs are rebuilt on every navigation, which would drop a keyboard user's focus.
// Remember which link had it, so the same link in the new tabs can take it back.
function focusedNavLink() {
  const focused = document.activeElement;
  if (!focused?.closest("#tabs, #subtabs") || !focused.matches(":focus-visible")) return null;
  return { href: focused.getAttribute("href"), isTab: focused.classList.contains("tab") };
}

function restoreNavFocus(remembered) {
  if (!remembered) return;
  // A country chosen in a region's menu continues in the country row, which stays visible.
  const container = remembered.isTab ? "#tabs .tab" : "#subtabs a";
  document.querySelector(`${container}[href="${CSS.escape(remembered.href)}"]`)?.focus();
}

function renderTabs(activeId) {
  const remembered = focusedNavLink();
  const active = DATA.sections.find(section => section.id === activeId);
  const list = el("ul", "tab-list");
  list.append(tabItem(SIGNALS_TAB, activeId));
  for (const { section, countries } of sectionTree()) {
    list.append(countries.length ? regionItem(section, countries, activeId) : tabItem(section, activeId));
  }
  list.append(tabItem(COMPARE_TAB, activeId));
  document.getElementById("tabs").replaceChildren(list);
  scrollToActiveTab(list);
  renderCountryRow(active?.region ?? activeId, activeId);
  restoreNavFocus(remembered);
}

// On a phone the tabs scroll sideways; centre the active one so it is always in view.
function scrollToActiveTab(list) {
  const activeTab = list.querySelector('.tab[aria-current="page"], .tab.is-active');
  if (!activeTab) return;
  const tabBox = activeTab.getBoundingClientRect();
  const listBox = list.getBoundingClientRect();
  list.scrollLeft += tabBox.left - listBox.left - (listBox.width - tabBox.width) / 2;
}

function renderSection(sectionId) {
  destroyCharts();
  const panels = DATA.panels.filter(panel => panel.section === sectionId);
  const cards = panels.map(renderCard);

  // A sub-heading goes in front of the first card of each group.
  const children = [];
  const recessionSource = DATA.sections.find(section => section.id === sectionId)?.recessions;
  if (recessionSource && RECESSION_NOTES[recessionSource]) {
    children.push(el("p", "section-note", RECESSION_NOTES[recessionSource]));
  }
  panels.forEach((panel, index) => {
    if (panel.group && panel.group !== panels[index - 1]?.group) {
      children.push(el("h2", "group-heading", panel.group));
    }
    children.push(cards[index]);
  });
  document.getElementById("panels").replaceChildren(...children);

  // Charts are created after the cards are in the page: Chart.js needs their size.
  for (const canvas of document.querySelectorAll("#panels canvas")) {
    if (typeof Chart === "undefined") {
      canvas.parentElement.replaceWith(el("p", "error-text", "⚠ Grafbiblioteket kunne ikke indlæses (ingen internetforbindelse?)"));
      continue;
    }
    activeCharts.push(createChart(canvas, canvas.chartPanel));
  }
}

function route() {
  const { sectionId, rangeYears: years, params } = parseHash();
  rangeYears = years;
  updateRangeButtons();
  renderTabs(sectionId);
  if (sectionId === SIGNALS_TAB.id) {
    renderSignals();
  } else if (sectionId === COMPARE_TAB.id) {
    renderCompare(params);
  } else {
    renderSection(sectionId);
  }
  if (scrollTargetPanelId) {
    document.getElementById(`panel-${scrollTargetPanelId}`)?.scrollIntoView({ block: "start" });
    scrollTargetPanelId = null;
  } else if (sectionId !== shownSectionId) {
    window.scrollTo(0, 0); // a new tab starts at the top; a new period keeps the position
  }
  shownSectionId = sectionId;
}

function init() {
  if (!DATA) {
    document.getElementById("load-error").hidden = false;
    return;
  }
  resolveReferences();
  if (typeof Chart !== "undefined") {
    Chart.Interaction.modes.nearestPerSeries = nearestPerSeries;
    // Registration order is drawing order: recession bands go behind the reference lines.
    Chart.register(recessionPlugin, referenceLinesPlugin, crosshairPlugin);
  }
  for (const button of document.querySelectorAll("#range-picker button")) {
    // Only changes the URL; the hashchange event then redraws the page from it.
    button.addEventListener("click", () => {
      const { sectionId, params } = parseHash();
      location.hash = hashFor(sectionId, Number(button.dataset.years), Object.fromEntries(params));
    });
  }
  renderUpdated();
  // Escape also closes a menu opened by hovering, where the focus is elsewhere.
  document.addEventListener("keydown", event => {
    if (event.key !== "Escape") return;
    for (const item of document.querySelectorAll('.tab-region[data-open="true"]')) setRegionOpen(item, false);
  });
  window.addEventListener("hashchange", route);
  // Chart colours are read from CSS when a chart is created, so redraw if the theme flips.
  window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", route);
  route();
}

init();
