"use strict";

// Generated by fetch_data.py (data/data.js). Undefined if the file is missing.
const DATA = window.MACRO_DATA;

// ------------------------------------------------------------------ formatting

const numberFormats = new Map();

function formatNumber(value, decimals) {
  const digits = Math.abs(value) >= 1000 ? 0 : decimals;
  if (!numberFormats.has(digits)) {
    numberFormats.set(digits, new Intl.NumberFormat("da-DK", {
      minimumFractionDigits: digits,
      maximumFractionDigits: digits,
    }));
  }
  return numberFormats.get(digits).format(value);
}

function changeUnit(panel) {
  if (panel.change === "pct") return " %";
  // A change in a percentage (a rate, a growth rate, a spread) is measured in %-points.
  return panel.unit.includes("%") ? " %-point" : "";
}

function changeDecimals(change, panel) {
  if (panel.change !== "pct") return panel.decimals;
  return Math.abs(change) < 1 ? 2 : 1; // small moves (e.g. the pegged EUR/DKK) need two decimals
}

// Sign and arrow follow the value as displayed, so a tiny move never shows as "▼ −0,00".
function roundedChange(change, panel) {
  const decimals = changeDecimals(change, panel);
  return { value: Number(change.toFixed(decimals)), decimals };
}

function formatChange(change, panel) {
  const { value, decimals } = roundedChange(change, panel);
  const sign = value > 0 ? "+" : value < 0 ? "−" : "±";
  return `${sign}${formatNumber(Math.abs(value), decimals)}${changeUnit(panel)}`;
}

// Dates in data.js are ISO dates for the first day of the period, so format in UTC
// to avoid a time zone shifting e.g. 2026-08-01 back to July.
const MONTH_FORMAT = new Intl.DateTimeFormat("da-DK", { month: "short", year: "numeric", timeZone: "UTC" });
const DAY_FORMAT = new Intl.DateTimeFormat("da-DK", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" });

function formatPeriod(isoDate, frequency) {
  const date = new Date(`${isoDate}T00:00:00Z`);
  switch (frequency) {
    case "A": return String(date.getUTCFullYear());
    case "Q": return `${Math.floor(date.getUTCMonth() / 3) + 1}. kvt. ${date.getUTCFullYear()}`;
    case "M": return MONTH_FORMAT.format(date);
    default: return DAY_FORMAT.format(date);
  }
}

function periodLabel(series) {
  const { lastDate } = series.summary;
  const isForecast = series.forecastFrom !== null && lastDate >= series.forecastFrom;
  return formatPeriod(lastDate, series.frequency) + (isForecast ? " (prognose)" : "");
}

// --------------------------------------------------------------------- DOM helpers

// Text always goes in through textContent: labels come from external APIs.
function el(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

function seriesColor(index) {
  return `var(--series-${index + 1})`;
}

function renderChange(change, panel) {
  const cell = el("dd");
  const { value } = roundedChange(change, panel);
  if (value !== 0) {
    const arrow = el("span", "arrow", value > 0 ? "▲" : "▼");
    arrow.setAttribute("aria-hidden", "true");
    cell.append(arrow);
  }
  cell.append(formatChange(change, panel));
  return cell;
}

// ---------------------------------------------------------------------- card parts

function renderHeadline(panel) {
  const primary = panel.series[0];
  const box = el("div", "headline");
  if (!primary.summary) {
    box.append(el("p", "error-text", `⚠ Data mangler (${primary.error ?? "ukendt fejl"})`));
    return box;
  }

  const row = el("div", "headline-row");
  const meta = panel.series.length > 1 ? `${primary.label} · ${periodLabel(primary)}` : periodLabel(primary);
  row.append(el("span", "headline-value", formatNumber(primary.summary.last, panel.decimals)),
             el("span", "headline-meta", meta));

  const deltas = el("dl", "deltas");
  for (const [label, change] of [["1 md.", primary.summary.change1m], ["1 år", primary.summary.change1y]]) {
    if (change === null) continue; // e.g. quarterly data has no 1-month change
    const item = el("div", "delta");
    item.append(el("dt", "", label), renderChange(change, panel));
    deltas.append(item);
  }
  const percentile = primary.summary.percentile10y; // undefined in data files from before this feature
  if (percentile !== null && percentile !== undefined) {
    const rank = Math.round(percentile);
    const item = el("div", "delta");
    const value = el("dd", "", `${rank}. percentil`);
    value.title = `Højere end ca. ${rank} % af målingerne de seneste 10 år`;
    item.append(el("dt", "", "Niveau, 10 år"), value);
    deltas.append(item);
  }
  box.append(row, deltas);
  return box;
}

function renderSeriesTable(panel) {
  const table = el("table", "series-table");
  table.append(el("caption", "visually-hidden", `Seneste værdier: ${panel.title}`));

  const headRow = el("tr");
  for (const [text, className] of [["Serie", ""], ["Seneste", "num"], ["1 år", "num"], ["Periode", "num period"]]) {
    headRow.append(el("th", className, text));
  }
  const head = el("thead");
  head.append(headRow);
  table.append(head);

  const body = el("tbody");
  panel.series.forEach((series, index) => {
    const row = el("tr");
    const swatch = el("span", "swatch");
    swatch.style.setProperty("--swatch", seriesColor(index));
    swatch.setAttribute("aria-hidden", "true");
    const nameText = el("div", "", series.label);
    const name = el("div", "series-name");
    name.append(swatch, nameText);
    const nameCell = el("td");
    nameCell.append(name);
    row.append(nameCell);

    if (series.summary) {
      const { last, change1y } = series.summary;
      const note = freshnessNote(series);
      const periodText = (note ? "⚠ " : "") + periodLabel(series);
      // On narrow screens the period column is hidden and this copy under the name shows instead.
      nameText.append(el("span", "period-inline", periodText));
      const period = el("td", "num period", periodText);
      if (note) period.title = note;
      row.append(
        el("td", "num", formatNumber(last, panel.decimals)),
        el("td", "num", change1y === null ? "–" : formatChange(change1y, panel)),
        period,
      );
    } else {
      const error = el("td", "num error-text", "⚠ Data mangler");
      error.colSpan = 3;
      error.title = series.error ?? "";
      row.append(error);
    }
    body.append(row);
  });
  table.append(body);
  return table;
}

// ------------------------------------------------------------ freshness + sources

const FETCH_TIME_FORMAT = new Intl.DateTimeFormat("da-DK", {
  day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit",
});
const FETCH_DATE_FORMAT = new Intl.DateTimeFormat("da-DK", { day: "numeric", month: "short", year: "numeric" });
const FREQUENCY_ADJECTIVES = { D: "daglige", W: "ugentlige", M: "månedlige", Q: "kvartalsvise", A: "årlige" };
const OLD_DATA_DAYS = 2; // the update job runs daily, so older data means it has stopped

function renderUpdated() {
  const fetchedAt = new Date(DATA.generatedAt);
  const ageDays = Math.floor((Date.now() - fetchedAt.getTime()) / 86_400_000);
  const node = document.getElementById("updated");
  const text = `Data hentet ${FETCH_TIME_FORMAT.format(fetchedAt)}`;
  if (ageDays >= OLD_DATA_DAYS) {
    node.textContent = `⚠ ${text} (${ageDays} dage siden – den daglige opdatering kører måske ikke)`;
    node.classList.add("is-old");
  } else {
    node.textContent = text;
  }
}

// Why a series' latest value might not be current, or null if it is.
function freshnessNote(series) {
  if (series.fallbackFrom) {
    return `Seneste hentning fejlede – viser data hentet ${FETCH_DATE_FORMAT.format(new Date(series.fallbackFrom))}`;
  }
  if (series.stale) {
    return `Forældet: nyeste tal er ældre end normalt for ${FREQUENCY_ADJECTIVES[series.frequency]} data`;
  }
  return null;
}

function renderNotes(panel) {
  const labelsByNote = new Map();
  for (const series of panel.series) {
    const note = freshnessNote(series);
    if (note === null) continue;
    if (!labelsByNote.has(note)) labelsByNote.set(note, []);
    labelsByNote.get(note).push(series.label);
  }
  if (labelsByNote.size === 0) return null;

  const list = el("ul", "notes");
  for (const [note, labels] of labelsByNote) {
    // A note that applies to every series in the card is said once, without naming them.
    const prefix = labels.length === panel.series.length ? "" : `${labels.join(", ")}: `;
    list.append(el("li", "", `⚠ ${prefix}${note}`));
  }
  return list;
}

function sourceLink(text, url) {
  if (!url) return text; // derived series are computed here, so there is nothing to link to
  const link = el("a", "", text);
  link.href = url;
  link.target = "_blank";
  link.rel = "noopener noreferrer";
  return link;
}

// "Kilde: FRED · Danmarks Statistik: Huse, Lejligheder" – one link per distinct page.
function renderSources(panel) {
  const seriesBySource = new Map();
  for (const series of panel.series) {
    if (!seriesBySource.has(series.source)) seriesBySource.set(series.source, []);
    seriesBySource.get(series.source).push(series);
  }

  const footer = el("p", "card-sources", "Kilde: ");
  [...seriesBySource].forEach(([source, members], groupIndex) => {
    if (groupIndex > 0) footer.append(" · ");
    const distinctUrls = new Set(members.map(series => series.sourceUrl));
    if (distinctUrls.size === 1) {
      footer.append(sourceLink(source, members[0].sourceUrl));
      return;
    }
    footer.append(`${source}: `);
    members.forEach((series, index) => {
      if (index > 0) footer.append(", ");
      footer.append(sourceLink(series.label, series.sourceUrl));
    });
  });
  return footer;
}

// ------------------------------------------------------------------------- CSV export

function csvField(text) {
  return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

// Long format (one row per observation), because the series of a panel can have
// different dates, e.g. daily and monthly gas prices.
function panelCsv(panel) {
  const rows = ["dato,serie,værdi"];
  for (const series of panel.series) {
    for (const [date, value] of series.data) rows.push(`${date},${csvField(series.label)},${value}`);
  }
  return rows.join("\n") + "\n";
}

function downloadCsv(panel) {
  // The BOM tells Excel the file is UTF-8, so æ, ø and å display correctly.
  const blob = new Blob(["﻿" + panelCsv(panel)], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = el("a");
  link.href = url;
  link.download = `${panel.id}.csv`;
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000); // give the browser time to start the download
}

function renderCsvButton(panel) {
  const button = el("button", "csv-button", "CSV");
  button.type = "button";
  button.title = "Download data som CSV. Dagsdata ældre end 2 år er tyndet ud til ét punkt pr. uge.";
  button.setAttribute("aria-label", `Download ${panel.title} som CSV`);
  button.addEventListener("click", () => downloadCsv(panel));
  return button;
}

function renderCard(panel) {
  const card = el("article", "card");
  const head = el("header", "card-head");
  head.append(el("h3", "card-title", panel.title), el("span", "card-unit", panel.unit));
  card.append(head, el("p", "card-desc", panel.description), renderHeadline(panel));
  if (panel.series.some(series => series.data.length > 0)) card.append(renderChartSlot(panel));
  if (panel.series.length > 1) card.append(renderSeriesTable(panel));
  const notes = renderNotes(panel);
  if (notes) card.append(notes);
  const footer = el("div", "card-footer");
  footer.append(renderSources(panel));
  if (panel.series.some(series => series.data.length > 0)) footer.append(renderCsvButton(panel));
  card.append(footer);
  return card;
}

// -------------------------------------------------------------------------- charts

const DEFAULT_RANGE_YEARS = 5; // short enough that 2020's outliers don't flatten every chart
let rangeYears = DEFAULT_RANGE_YEARS; // 0 = all data
let activeCharts = [];

const AXIS_NUMBER_FORMAT = new Intl.NumberFormat("da-DK", { maximumFractionDigits: 2 });
// Local time on purpose: the date adapter places ticks at local midnight, so in UTC
// "1 Jan 2022 00:00" in Copenhagen would still be 2021.
const AXIS_MONTH_FORMAT = new Intl.DateTimeFormat("da-DK", { month: "short", year: "2-digit" });

function cssVar(name) {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
}

function isoDate(timestamp) {
  return new Date(timestamp).toISOString().slice(0, 10);
}

function rangeStart(years) {
  if (years === 0) return undefined;
  // Counted back from when the data was fetched, so an old data file still shows its data.
  const start = new Date(DATA.generatedAt);
  start.setUTCFullYear(start.getUTCFullYear() - years);
  return start.getTime();
}

function timeUnit(years) {
  return years === 1 ? "month" : "year";
}

function formatAxisDate(timestamp) {
  const date = new Date(timestamp);
  return rangeYears === 1 ? AXIS_MONTH_FORMAT.format(date) : String(date.getFullYear());
}

// Binary search for the point closest to pixel x; points are sorted by date.
function nearestIndex(points, x) {
  let low = 0;
  let high = points.length - 1;
  while (low < high) {
    const middle = (low + high) >> 1;
    if (points[middle].x < x) low = middle + 1;
    else high = middle;
  }
  const previousIsCloser = low > 0 && x - points[low - 1].x < points[low].x - x;
  return previousIsCloser ? low - 1 : low;
}

// Hover mode: the point closest to the pointer in *each* series. Chart.js' built-in
// "index" mode assumes all series share the same dates, which mixed daily/monthly
// series and rates from different central banks don't.
function nearestPerSeries(chart, event) {
  const { left, right } = chart.chartArea;
  const items = [];
  chart.data.datasets.forEach((dataset, datasetIndex) => {
    const points = chart.getDatasetMeta(datasetIndex).data;
    if (points.length === 0) return;
    const index = nearestIndex(points, event.x);
    const point = points[index];
    if (point.x >= left && point.x <= right) items.push({ element: point, datasetIndex, index });
  });
  return items;
}

// A vertical hairline at the hovered date.
const crosshairPlugin = {
  id: "crosshair",
  afterDatasetsDraw(chart) {
    const active = chart.tooltip?.getActiveElements() ?? [];
    if (active.length === 0) return;
    const x = active[0].element.x;
    const { ctx, chartArea } = chart;
    ctx.save();
    ctx.strokeStyle = cssVar("--baseline");
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(x, chartArea.top);
    ctx.lineTo(x, chartArea.bottom);
    ctx.stroke();
    ctx.restore();
  },
};

// Grey bands behind the lines for recessions, so turning points read in context.
const recessionPlugin = {
  id: "recessions",
  beforeDatasetsDraw(chart, args, options) {
    const periods = options.periods ?? [];
    if (periods.length === 0) return;
    const { ctx, chartArea, scales } = chart;
    ctx.save();
    ctx.fillStyle = cssVar("--recession");
    for (const [start, end] of periods) {
      const left = Math.max(scales.x.getPixelForValue(start), chartArea.left);
      const right = Math.min(scales.x.getPixelForValue(end), chartArea.right);
      if (right > left) ctx.fillRect(left, chartArea.top, right - left, chartArea.bottom - chartArea.top);
    }
    ctx.restore();
  },
};

const RECESSION_NOTES = {
  us: "Grå felter: recessioner i USA (NBER).",
  euro_area: "Grå felter: recessioner i eurozonen (CEPR).",
};

function recessionPeriods(sectionId) {
  const source = DATA.sections.find(section => section.id === sectionId)?.recessions;
  const periods = (source && DATA.recessions?.[source]) ?? [];
  return periods.map(([start, end]) => [Date.parse(start), Date.parse(end)]);
}

// Dashed horizontal lines for targets and thresholds (e.g. a 2 % inflation target).
// Dashed on purpose, so they read as a threshold and not as one more gridline.
const referenceLinesPlugin = {
  id: "referenceLines",
  beforeDatasetsDraw(chart, args, options) {
    const lines = options.lines ?? [];
    if (lines.length === 0) return;
    const { ctx, chartArea, scales } = chart;
    ctx.save();
    ctx.strokeStyle = cssVar("--text-muted");
    ctx.fillStyle = cssVar("--text-muted");
    ctx.lineWidth = 1;
    ctx.setLineDash([4, 4]);
    ctx.font = "11px system-ui, -apple-system, sans-serif";
    ctx.textAlign = "right";
    ctx.textBaseline = "bottom";
    for (const { value, label } of lines) {
      const y = scales.y.getPixelForValue(value);
      if (y < chartArea.top || y > chartArea.bottom) continue;
      ctx.beginPath();
      ctx.moveTo(chartArea.left, y);
      ctx.lineTo(chartArea.right, y);
      ctx.stroke();
      ctx.fillText(label, chartArea.right - 2, y - 2);
    }
    ctx.restore();
  },
};

function tooltipPeriod(item) {
  const date = isoDate(item.parsed.x);
  const { frequency, forecastFrom } = item.dataset;
  const isForecast = forecastFrom !== null && date >= forecastFrom;
  return formatPeriod(date, frequency) + (isForecast ? " (prognose)" : "");
}

function tooltipOptions(panel) {
  return {
    backgroundColor: cssVar("--surface"),
    borderColor: cssVar("--border"),
    borderWidth: 1,
    titleColor: cssVar("--text-secondary"),
    titleFont: { weight: "normal" },
    bodyColor: cssVar("--text-primary"),
    padding: 8,
    usePointStyle: true,
    callbacks: {
      title: items => tooltipPeriod(items[0]),
      // A regular function: Chart.js passes the tooltip as `this`, which holds all rows.
      label(item) {
        const value = formatNumber(item.parsed.y, panel.decimals);
        const period = tooltipPeriod(item);
        const ownDate = period === tooltipPeriod(this.dataPoints[0]) ? "" : ` (${period})`;
        return panel.series.length > 1 ? `${value}  ${item.dataset.label}${ownDate}` : value + ownDate;
      },
      labelPointStyle: () => ({ pointStyle: "line", rotation: 0 }),
    },
  };
}

function buildDatasets(panel) {
  const surface = cssVar("--surface");
  return panel.series.map((series, index) => {
    const color = cssVar(`--series-${index + 1}`);
    const forecastStart = series.forecastFrom ? Date.parse(series.forecastFrom) : null;
    return {
      label: series.label,
      frequency: series.frequency, // our own fields, read by the tooltip
      forecastFrom: series.forecastFrom,
      data: series.data.map(([date, value]) => ({ x: Date.parse(date), y: value })),
      borderColor: color,
      backgroundColor: color,
      borderWidth: 2,
      pointRadius: 0,
      pointHoverRadius: 4,
      pointHoverBorderWidth: 2,
      pointHoverBorderColor: surface,
      // Forecast years are dashed, so a projection never passes for data.
      segment: forecastStart === null ? undefined : {
        borderDash: context => (context.p1.parsed.x >= forecastStart ? [4, 4] : undefined),
      },
    };
  });
}

function chartOptions(panel) {
  const gridColor = cssVar("--gridline");
  const zeroLineColor = cssVar("--baseline");
  const tickColor = cssVar("--text-muted");
  const referenceLines = panel.referenceLines ?? []; // missing in data files from before this feature
  const referenceValues = referenceLines.map(line => line.value);
  return {
    animation: false,
    maintainAspectRatio: false,
    parsing: false, // data is already {x, y} ...
    normalized: true, // ... and sorted by date, so Chart.js can skip that work
    interaction: { mode: "nearestPerSeries", intersect: false },
    plugins: {
      legend: { display: false },
      tooltip: tooltipOptions(panel),
      referenceLines: { lines: referenceLines },
      recessions: { periods: recessionPeriods(panel.section) },
    },
    scales: {
      x: {
        type: "time",
        min: rangeStart(rangeYears),
        time: { unit: timeUnit(rangeYears) },
        grid: { display: false },
        border: { color: zeroLineColor },
        ticks: { color: tickColor, maxRotation: 0, maxTicksLimit: 6, callback: formatAxisDate },
      },
      y: {
        // Stretch the axis so every reference line stays visible, e.g. a 2 % target
        // when inflation has been above 3 % for the whole period.
        suggestedMin: referenceValues.length ? Math.min(...referenceValues) : undefined,
        suggestedMax: referenceValues.length ? Math.max(...referenceValues) : undefined,
        border: { display: false },
        // A stronger line at zero: crossing it matters for spreads, growth and job gains.
        grid: { color: context => (context.tick.value === 0 ? zeroLineColor : gridColor) },
        // 6, not 5: with 5, a value just below zero (Japan's −0.1 %) needs one extra step,
        // so Chart.js jumps to a coarser step and leaves half the axis empty.
        ticks: { color: tickColor, maxTicksLimit: 6, callback: value => AXIS_NUMBER_FORMAT.format(value) },
      },
    },
  };
}

function renderChartSlot(panel) {
  const slot = el("div", "chart");
  const canvas = el("canvas");
  canvas.setAttribute("role", "img");
  canvas.setAttribute("aria-label", `Graf: ${panel.title}`);
  slot.append(canvas);
  return slot;
}

function createChart(canvas, panel) {
  return new Chart(canvas, { type: "line", data: { datasets: buildDatasets(panel) }, options: chartOptions(panel) });
}

function destroyCharts() {
  for (const chart of activeCharts) chart.destroy(); // frees the canvases of the previous tab
  activeCharts = [];
}

function updateRangeButtons() {
  for (const button of document.querySelectorAll("#range-picker button")) {
    button.setAttribute("aria-pressed", String(Number(button.dataset.years) === rangeYears));
  }
}

// ---------------------------------------------------------------- sections + routing

// The URL is the single source of truth for what is shown: "#europe?range=10" means the
// Europe tab with 10 years of history. So a copied link, a reload or the back button
// restores exactly the same view. The default range is left out to keep links short.
const VALID_RANGES = [1, 5, 10, 0];

function parseHash() {
  const [sectionPart, query = ""] = location.hash.slice(1).split("?");
  const params = new URLSearchParams(query);
  const range = Number(params.get("range"));
  return {
    sectionId: DATA.sections.some(section => section.id === sectionPart) ? sectionPart : DATA.sections[0].id,
    rangeYears: params.has("range") && VALID_RANGES.includes(range) ? range : DEFAULT_RANGE_YEARS,
  };
}

function hashFor(sectionId, years) {
  return years === DEFAULT_RANGE_YEARS ? `#${sectionId}` : `#${sectionId}?range=${years}`;
}

function renderTabs(activeId) {
  const links = DATA.sections.map(section => {
    const link = el("a", "tab", section.title);
    link.href = hashFor(section.id, rangeYears); // switching tab keeps the chosen period
    if (section.id === activeId) link.setAttribute("aria-current", "page");
    return link;
  });
  document.getElementById("tabs").replaceChildren(...links);
}

function renderSection(sectionId) {
  destroyCharts();
  const panels = DATA.panels.filter(panel => panel.section === sectionId);
  const cards = panels.map(renderCard);

  // A sub-heading goes in front of the first card of each group.
  const children = [];
  const recessionSource = DATA.sections.find(section => section.id === sectionId)?.recessions;
  if (recessionSource && RECESSION_NOTES[recessionSource]) {
    children.push(el("p", "section-note", RECESSION_NOTES[recessionSource]));
  }
  panels.forEach((panel, index) => {
    if (panel.group && panel.group !== panels[index - 1]?.group) {
      children.push(el("h2", "group-heading", panel.group));
    }
    children.push(cards[index]);
  });
  document.getElementById("panels").replaceChildren(...children);

  // Charts are created after the cards are in the page: Chart.js needs their size.
  panels.forEach((panel, index) => {
    const canvas = cards[index].querySelector("canvas");
    if (!canvas) return;
    if (typeof Chart === "undefined") {
      canvas.parentElement.replaceWith(el("p", "error-text", "⚠ Grafbiblioteket kunne ikke indlæses (ingen internetforbindelse?)"));
      return;
    }
    activeCharts.push(createChart(canvas, panel));
  });
}

function route() {
  const { sectionId, rangeYears: years } = parseHash();
  rangeYears = years;
  updateRangeButtons();
  renderTabs(sectionId);
  renderSection(sectionId);
}

function init() {
  if (!DATA) {
    document.getElementById("load-error").hidden = false;
    return;
  }
  if (typeof Chart !== "undefined") {
    Chart.Interaction.modes.nearestPerSeries = nearestPerSeries;
    // Registration order is drawing order: recession bands go behind the reference lines.
    Chart.register(recessionPlugin, referenceLinesPlugin, crosshairPlugin);
  }
  for (const button of document.querySelectorAll("#range-picker button")) {
    // Only changes the URL; the hashchange event then redraws the page from it.
    button.addEventListener("click", () => {
      location.hash = hashFor(parseHash().sectionId, Number(button.dataset.years));
    });
  }
  renderUpdated();
  window.addEventListener("hashchange", route);
  // Chart colours are read from CSS when a chart is created, so redraw if the theme flips.
  window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", route);
  route();
}

init();
