"""Catalog of every indicator shown on the dashboard.

A Panel is one card on the page (one chart). It holds one or more Series.
The first series in a panel is the "primary" one whose latest value is
shown as the headline number.

Query format per source:
    fred      FRED series id                       "DGS10"
    ecb       ECB flow/key                         "FM/D.U2.EUR.4F.KR.DFR.LEV"
    eurostat  dataset?filters                      "prc_hicp_minr?geo=EA&coicop18=TOTAL&unit=RCH_A"
    bis       WS_CBPOL key (policy rates)          "D.US"
    imf_weo   IMF DataMapper indicator/country     "NGDP_RPCH/WEOWORLD"
    imf_cpi   IMF CPI year-over-year, country      "JPN"
    oecd_lt   OECD 10-year government bond yield   "DEU"
    statbank  Statistics Denmark table?filters     "AUS08?OMRÅDE=000&SAESONFAK=9"
    derived   computed from other series           ("it_10y", "de_10y")
"""

from dataclasses import dataclass

SECTIONS: list[tuple[str, str]] = [
    ("global", "Global"),
    ("us", "USA"),
    ("europe", "Europa"),
    ("denmark", "Danmark"),
    ("asia", "Asien"),
    ("china", "Kina"),
    ("japan", "Japan"),
    ("korea", "Sydkorea"),
]


@dataclass(frozen=True)
class Series:
    key: str
    label: str
    source: str
    query: str | tuple[str, str]
    # None = use as delivered; "yoy" = % change vs. same period last year;
    # "diff" = change vs. previous observation; "spread" = a - b in %-points.
    transform: str | None = None


@dataclass(frozen=True)
class Panel:
    id: str
    section: str
    title: str
    unit: str
    description: str
    series: tuple[Series, ...]
    # How headline changes are shown: "diff" = difference in the unit (%-points for rates),
    # "pct" = percent change (prices, indices, exchange rates).
    change: str = "diff"
    decimals: int = 2  # values >= 1000 are always shown without decimals
    # Optional sub-heading within the section. Panels of one group must be adjacent.
    group: str | None = None
    # Horizontal reference lines as (value, label), e.g. an inflation target.
    reference_lines: tuple[tuple[float, str], ...] = ()


# Euro area recessions as (peak quarter, trough quarter) from the CEPR-EABCN Business Cycle
# Dating Committee, checked 2026-10-07 at
# https://eabcn.org/dbc/peaksandtroughs/chronology-euro-area-business-cycles
# The committee has no API, so a new decision must be added here by hand. Earlier
# recessions (1974–1993) are left out: the dashboard starts in 2000.
EURO_AREA_PEAKS_AND_TROUGHS = [("2008-Q1", "2009-Q2"), ("2011-Q3", "2013-Q1"), ("2019-Q4", "2020-Q2")]

# Which recession dating is shaded behind the charts of each section.
RECESSIONS_BY_SECTION = {"us": "us", "europe": "euro_area", "denmark": "euro_area"}

INFLATION_TARGET_FED = ((2.0, "Fed-mål 2 %"),)
INFLATION_TARGET_ECB = ((2.0, "ECB-mål 2 %"),)


def S(key: str, label: str, source: str, query, transform: str | None = None) -> Series:
    return Series(key, label, source, query, transform)


PANELS: list[Panel] = [
    # ------------------------------------------------------------------ GLOBAL
    Panel("oil", "global", "Olie", "USD/tønde",
          "Råoliepris. Påvirker inflation, handelsbalancer og centralbankernes renteudsigter.",
          (S("brent", "Brent", "fred", "DCOILBRENTEU"),
           S("wti", "WTI", "fred", "DCOILWTICO")), change="pct"),
    Panel("gas", "global", "Naturgas", "USD/MMBtu",
          "Gaspris i USA (Henry Hub, daglig) og Europa (månedlig). Vigtig for europæisk energiinflation.",
          (S("gas_us", "Henry Hub (USA)", "fred", "DHHNGSP"),
           S("gas_eu", "Europa", "fred", "PNGASEUUSDM")), change="pct"),
    Panel("copper", "global", "Kobber", "USD/ton",
          "Kaldes 'Dr. Copper': følsom over for global industriproduktion og byggeri.",
          (S("copper", "Kobber", "fred", "PCOPPUSDM"),), change="pct"),
    Panel("wheat", "global", "Hvede", "USD/ton",
          "Global fødevarepris. Driver fødevareinflation, især i emerging markets.",
          (S("wheat", "Hvede", "fred", "PWHEAMTUSDM"),), change="pct"),
    Panel("dollar", "global", "Dollarindeks (bredt)", "Indeks",
          "Dollarens styrke mod handelspartnere. Stærk dollar strammer globale finansielle forhold.",
          (S("usd_broad", "Bredt dollarindeks", "fred", "DTWEXBGS"),), change="pct"),
    Panel("vix", "global", "VIX – frygtindeks", "Indeks",
          "Forventet volatilitet i S&P 500 de næste 30 dage. Over ~30 = stress på markederne.",
          (S("vix", "VIX", "fred", "VIXCLS"),)),
    Panel("policy_rates", "global", "Styringsrenter", "%",
          "Centralbankernes officielle renter side om side.",
          (S("pr_us", "USA (Fed)", "bis", "D.US"),
           S("pr_ea", "Eurozone (ECB)", "bis", "D.XM"),
           S("pr_gb", "UK (BoE)", "bis", "D.GB"),
           S("pr_jp", "Japan (BoJ)", "bis", "D.JP"),
           S("pr_cn", "Kina (PBoC)", "bis", "D.CN"),
           S("pr_dk", "Danmark (NB)", "bis", "D.DK"),
           S("pr_ch", "Schweiz (SNB)", "bis", "D.CH"))),
    Panel("world_gdp", "global", "BNP-vækst inkl. IMF-prognose", "% år/år",
          "Real BNP-vækst. Indeværende og kommende år er IMF-prognoser (World Economic Outlook).",
          (S("gdp_world", "Verden", "imf_weo", "NGDP_RPCH/WEOWORLD"),
           S("gdp_adv", "Avancerede økonomier", "imf_weo", "NGDP_RPCH/ADVEC"),
           S("gdp_em", "Emerging markets", "imf_weo", "NGDP_RPCH/OEMDC"))),
    Panel("world_infl", "global", "Inflation inkl. IMF-prognose", "% år/år",
          "Gennemsnitlig forbrugerprisinflation. Indeværende og kommende år er IMF-prognoser.",
          (S("infl_world", "Verden", "imf_weo", "PCPIPCH/WEOWORLD"),
           S("infl_adv", "Avancerede økonomier", "imf_weo", "PCPIPCH/ADVEC"),
           S("infl_em", "Emerging markets", "imf_weo", "PCPIPCH/OEMDC"))),

    # --------------------------------------------------------------------- USA
    Panel("us_fed", "us", "Fed funds-rente", "%",
          "Fed's målinterval (øvre/nedre) og den faktiske effektive rente.",
          (S("us_ffr", "Effektiv rente", "fred", "DFF"),
           S("us_ff_upper", "Mål (øvre)", "fred", "DFEDTARU"),
           S("us_ff_lower", "Mål (nedre)", "fred", "DFEDTARL"))),
    Panel("us_yields", "us", "Statsrenter (Treasuries)", "%",
          "Renten på amerikanske statsobligationer: verdens vigtigste 'risikofri' rente.",
          (S("us_10y", "10 år", "fred", "DGS10"),
           S("us_3m", "3 mdr.", "fred", "DGS3MO"),
           S("us_2y", "2 år", "fred", "DGS2"),
           S("us_30y", "30 år", "fred", "DGS30"))),
    Panel("us_curve", "us", "Rentekurve-spreads", "%-point",
          "Forskel mellem lang og kort rente. Negativ (inverteret kurve) har historisk varslet recession.",
          (S("us_10y2y", "10 år − 2 år", "fred", "T10Y2Y"),
           S("us_10y3m", "10 år − 3 mdr.", "fred", "T10Y3M"))),
    Panel("us_credit", "us", "Kreditspreads", "%-point",
          "Merrente på virksomhedsobligationer over statsrenter. Stiger når markedet frygter konkurser.",
          (S("us_hy", "High yield", "fred", "BAMLH0A0HYM2"),
           S("us_ig", "Investment grade", "fred", "BAMLC0A0CM"))),
    Panel("us_inflation", "us", "Inflation", "% år/år",
          "Forbrugerpriser (CPI) og Fed's foretrukne mål: kerne-PCE. Fed sigter efter 2 %.",
          (S("us_cpi", "CPI", "fred", "CPIAUCSL", "yoy"),
           S("us_core_cpi", "Kerne-CPI", "fred", "CPILFESL", "yoy"),
           S("us_core_pce", "Kerne-PCE", "fred", "PCEPILFE", "yoy")),
          reference_lines=INFLATION_TARGET_FED),
    Panel("us_breakeven", "us", "Inflationsforventning (10 år)", "%",
          "Markedets forventede gennemsnitlige inflation de næste 10 år (breakeven).",
          (S("us_be10", "10-årig breakeven", "fred", "T10YIE"),)),
    Panel("us_unemployment", "us", "Ledighed", "%",
          "Arbejdsløshedsprocent. Halvdelen af Fed's dobbelte mandat.",
          (S("us_unrate", "Ledighed", "fred", "UNRATE"),)),
    Panel("us_payrolls", "us", "Nye job (nonfarm payrolls)", "1.000 job/md.",
          "Månedlig ændring i antal lønmodtagere uden for landbruget.",
          (S("us_nfp", "Ændring i job", "fred", "PAYEMS", "diff"),)),
    Panel("us_claims", "us", "Nye ledighedsansøgninger", "Antal/uge",
          "Ugentlige førstegangsansøgninger om dagpenge. Tidlig indikator for arbejdsmarkedet.",
          (S("us_icsa", "Ansøgninger", "fred", "ICSA"),), change="pct"),
    Panel("us_gdp", "us", "BNP-vækst", "% (annualiseret k/k)",
          "Real BNP-vækst i kvartalet, omregnet til årlig takt.",
          (S("us_gdp", "Real BNP", "fred", "A191RL1Q225SBEA"),)),
    Panel("us_sentiment", "us", "Forbrugertillid", "Indeks",
          "University of Michigan Consumer Sentiment.",
          (S("us_umcsent", "Forbrugertillid", "fred", "UMCSENT"),)),
    Panel("us_mortgage", "us", "30-årig boligrente", "%",
          "Gennemsnitlig rente på nye 30-årige fastforrentede boliglån.",
          (S("us_mort30", "30-årig fast", "fred", "MORTGAGE30US"),)),
    Panel("us_equities", "us", "S&P 500", "Indeks",
          "De 500 største amerikanske aktier.",
          (S("sp500", "S&P 500", "fred", "SP500"),), change="pct"),

    # ------------------------------------------------------------------ EUROPA
    Panel("ecb_rates", "europe", "ECB-renter", "%",
          "ECB styrer med indlånsrenten. €STR er den faktiske dag-til-dag-rente mellem banker.",
          (S("ecb_dfr", "Indlånsrente", "ecb", "FM/D.U2.EUR.4F.KR.DFR.LEV"),
           S("ecb_mro", "Refinansieringsrente", "ecb", "FM/D.U2.EUR.4F.KR.MRR_FR.LEV"),
           S("estr", "€STR", "ecb", "EST/B.EU000A2X2A25.WT")),
          group="Renter og spreads"),
    Panel("ea_rate_expectation", "europe", "Markedets renteforventning", "%-point",
          "2-årig AAA-rente minus ECB's indlånsrente. Negativ: markedet venter rentenedsættelser. "
          "Positiv: markedet venter stigninger.",
          (S("ea_2y_dfr", "2 år − ECB-rente", "derived", ("ea_2y", "ecb_dfr"), "spread"),),
          group="Renter og spreads"),
    Panel("ea_curve", "europe", "Eurozone-rentekurve (AAA)", "%",
          "Renter på AAA-ratede eurozone-statsobligationer (ECB's daglige rentekurve).",
          (S("ea_10y", "10 år", "ecb", "YC/B.U2.EUR.4F.G_N_A.SV_C_YM.SR_10Y"),
           S("ea_2y", "2 år", "ecb", "YC/B.U2.EUR.4F.G_N_A.SV_C_YM.SR_2Y")),
          group="Renter og spreads"),
    Panel("ea_curve_spread", "europe", "Rentekurve-spread (AAA)", "%-point",
          "10-årig minus 2-årig AAA-rente. Negativ (inverteret kurve) har historisk varslet svag vækst.",
          (S("ea_10y2y", "10 år − 2 år", "derived", ("ea_10y", "ea_2y"), "spread"),),
          group="Renter og spreads"),
    Panel("eu_10y", "europe", "10-årige statsrenter: Tyskland og Frankrig", "%",
          "Månedlige gennemsnit for eurozonens to største økonomier.",
          (S("de_10y", "Tyskland", "oecd_lt", "DEU"),
           S("fr_10y", "Frankrig", "oecd_lt", "FRA")),
          group="Renter og spreads"),
    Panel("eu_10y_south", "europe", "10-årige statsrenter: Sydeuropa", "%",
          "Månedlige gennemsnit for de lande, der var i centrum af gældskrisen i 2010–2012.",
          (S("it_10y", "Italien", "oecd_lt", "ITA"),
           S("es_10y", "Spanien", "oecd_lt", "ESP"),
           S("gr_10y", "Grækenland", "oecd_lt", "GRC"),
           S("pt_10y", "Portugal", "oecd_lt", "PRT")),
          group="Renter og spreads"),
    Panel("eu_spreads", "europe", "Statsrente-spreads til Tyskland", "%-point",
          "Merrente over tyske statsobligationer. Måler uro om gæld i eurozonen.",
          (S("btp_bund", "Italien − Tyskland", "derived", ("it_10y", "de_10y"), "spread"),
           S("oat_bund", "Frankrig − Tyskland", "derived", ("fr_10y", "de_10y"), "spread"),
           S("bono_bund", "Spanien − Tyskland", "derived", ("es_10y", "de_10y"), "spread"),
           S("ggb_bund", "Grækenland − Tyskland", "derived", ("gr_10y", "de_10y"), "spread"),
           S("pgb_bund", "Portugal − Tyskland", "derived", ("pt_10y", "de_10y"), "spread")),
          group="Renter og spreads"),
    Panel("ea_inflation", "europe", "Inflation (HICP)", "% år/år",
          "Eurozonens harmoniserede forbrugerpriser. ECB sigter efter 2 %.",
          (S("ea_hicp", "HICP", "eurostat", "prc_hicp_minr?geo=EA&coicop18=TOTAL&unit=RCH_A"),
           S("ea_core", "Kerne (ekskl. energi og fødevarer)", "eurostat",
             "prc_hicp_minr?geo=EA&coicop18=TOT_X_NRG_FOOD&unit=RCH_A"),
           S("ea_services", "Serviceydelser", "eurostat", "prc_hicp_minr?geo=EA&coicop18=SERV&unit=RCH_A")),
          group="Inflation", reference_lines=INFLATION_TARGET_ECB),
    # Eurostat rather than ECB: the ECB's copy of this series lagged a quarter behind.
    Panel("ea_gdp", "europe", "BNP-vækst (eurozonen)", "% år/år",
          "Real BNP-vækst sammenlignet med samme kvartal året før.",
          (S("ea_gdp", "Real BNP", "eurostat", "namq_10_gdp?geo=EA&na_item=B1GQ&unit=CLV_PCH_SM&s_adj=SCA"),),
          group="Vækst og aktivitet"),
    Panel("ea_unemployment", "europe", "Ledighed (eurozonen)", "%",
          "Sæsonkorrigeret arbejdsløshed i eurozonen.",
          (S("ea_unrate", "Ledighed", "ecb", "LFSI/M.I9.S.UNEHRT.TOTAL0.15_74.T"),),
          group="Vækst og aktivitet"),
    # Eurostat's euro area code is EA21 since Bulgaria joined in 2026 (EA20 stops in 2025).
    # Year-over-year rates are only published for calendar-adjusted (CA) data.
    Panel("ea_sentiment", "europe", "Økonomisk stemning (ESI)", "Indeks",
          "EU-Kommissionens samlede stemningsindikator for erhverv og forbrugere. 100 = langsigtet gennemsnit.",
          (S("ea_esi", "ESI (eurozonen)", "eurostat", "ei_bssi_m_r2?geo=EA21&indic=BS-ESI-I&s_adj=SA"),),
          group="Vækst og aktivitet", reference_lines=((100.0, "Gennemsnit"),)),
    Panel("ea_industry", "europe", "Industriproduktion", "% år/år",
          "Produktion i industrien (ekskl. byggeri). Tyskland er eurozonens industrielle motor.",
          (S("de_ip", "Tyskland", "eurostat", "sts_inpr_m?geo=DE&indic_bt=PRD&nace_r2=B-D&s_adj=CA&unit=PCH_SM"),
           S("ea_ip", "Eurozonen", "eurostat",
             "sts_inpr_m?geo=EA21&indic_bt=PRD&nace_r2=B-D&s_adj=CA&unit=PCH_SM")),
          group="Vækst og aktivitet"),
    Panel("ea_retail", "europe", "Detailsalg (volumen)", "% år/år",
          "Detailhandlens salg målt i mængder. En direkte måling af forbrugernes efterspørgsel.",
          (S("ea_retail", "Eurozonen", "eurostat",
             "sts_trtu_m?geo=EA21&indic_bt=VOL_SLS&nace_r2=G47&s_adj=CA&unit=PCH_SM"),),
          group="Vækst og aktivitet"),
    Panel("eu_country_inflation", "europe", "Inflation pr. land (HICP)", "% år/år",
          "Harmoniseret forbrugerprisinflation i eurozonens fire største økonomier.",
          (S("de_hicp", "Tyskland", "eurostat", "prc_hicp_minr?geo=DE&coicop18=TOTAL&unit=RCH_A"),
           S("fr_hicp", "Frankrig", "eurostat", "prc_hicp_minr?geo=FR&coicop18=TOTAL&unit=RCH_A"),
           S("it_hicp", "Italien", "eurostat", "prc_hicp_minr?geo=IT&coicop18=TOTAL&unit=RCH_A"),
           S("es_hicp", "Spanien", "eurostat", "prc_hicp_minr?geo=ES&coicop18=TOTAL&unit=RCH_A")),
          group="Lande", reference_lines=INFLATION_TARGET_ECB),
    Panel("eu_country_unemployment", "europe", "Ledighed pr. land", "%",
          "Sæsonkorrigeret arbejdsløshed (15–74 år).",
          (S("de_unrate", "Tyskland", "eurostat", "une_rt_m?geo=DE&age=TOTAL&sex=T&s_adj=SA&unit=PC_ACT"),
           S("fr_unrate", "Frankrig", "eurostat", "une_rt_m?geo=FR&age=TOTAL&sex=T&s_adj=SA&unit=PC_ACT"),
           S("it_unrate", "Italien", "eurostat", "une_rt_m?geo=IT&age=TOTAL&sex=T&s_adj=SA&unit=PC_ACT"),
           S("es_unrate", "Spanien", "eurostat", "une_rt_m?geo=ES&age=TOTAL&sex=T&s_adj=SA&unit=PC_ACT")),
          group="Lande"),
    Panel("eu_country_gdp", "europe", "BNP-vækst pr. land", "% år/år",
          "Real BNP-vækst sammenlignet med samme kvartal året før.",
          (S("de_gdp", "Tyskland", "eurostat", "namq_10_gdp?geo=DE&na_item=B1GQ&unit=CLV_PCH_SM&s_adj=SCA"),
           S("fr_gdp", "Frankrig", "eurostat", "namq_10_gdp?geo=FR&na_item=B1GQ&unit=CLV_PCH_SM&s_adj=SCA"),
           S("it_gdp", "Italien", "eurostat", "namq_10_gdp?geo=IT&na_item=B1GQ&unit=CLV_PCH_SM&s_adj=SCA"),
           S("es_gdp", "Spanien", "eurostat", "namq_10_gdp?geo=ES&na_item=B1GQ&unit=CLV_PCH_SM&s_adj=SCA")),
          group="Lande"),
    Panel("eu_country_debt", "europe", "Statsgæld pr. land", "% af BNP",
          "Offentlig bruttogæld. Indeværende og kommende år er IMF-prognoser.",
          (S("de_debt", "Tyskland", "imf_weo", "GGXWDG_NGDP/DEU"),
           S("fr_debt", "Frankrig", "imf_weo", "GGXWDG_NGDP/FRA"),
           S("it_debt", "Italien", "imf_weo", "GGXWDG_NGDP/ITA"),
           S("es_debt", "Spanien", "imf_weo", "GGXWDG_NGDP/ESP")),
          group="Lande"),
    Panel("eu_country_balance", "europe", "Budgetsaldo pr. land", "% af BNP",
          "Offentligt overskud (+) eller underskud (−). EU's grænse er −3 %. "
          "Indeværende og kommende år er IMF-prognoser.",
          (S("de_balance", "Tyskland", "imf_weo", "GGXCNL_NGDP/DEU"),
           S("fr_balance", "Frankrig", "imf_weo", "GGXCNL_NGDP/FRA"),
           S("it_balance", "Italien", "imf_weo", "GGXCNL_NGDP/ITA"),
           S("es_balance", "Spanien", "imf_weo", "GGXCNL_NGDP/ESP")),
          group="Lande", reference_lines=((-3.0, "EU-grænse −3 %"),)),
    Panel("ea_lending", "europe", "Udlånsrenter i eurozonen", "%",
          "Bankernes samlede lånerente for virksomheder og for boliglån til husholdninger.",
          (S("ea_lend_nfc", "Virksomheder", "ecb", "MIR/M.U2.B.A2I.AM.R.A.2240.EUR.N"),
           S("ea_lend_hh", "Boliglån", "ecb", "MIR/M.U2.B.A2C.AM.R.A.2250.EUR.N")),
          group="Kredit og penge"),
    Panel("ea_loan_growth", "europe", "Udlånsvækst", "% år/år",
          "Vækst i bankernes udlån. Viser mere direkte end M3, om de højere renter bider.",
          (S("ea_loans_nfc", "Virksomheder", "ecb", "BSI/M.U2.Y.U.A20T.A.I.U2.2240.Z01.A"),
           S("ea_loans_hh", "Husholdninger", "ecb", "BSI/M.U2.Y.U.A20T.A.I.U2.2250.Z01.A")),
          group="Kredit og penge"),
    Panel("ea_m3", "europe", "Pengemængde M3", "% år/år",
          "Vækst i pengemængden. Lav vækst kan signalere stram kreditgivning.",
          (S("ea_m3", "M3", "ecb", "BSI/M.U2.Y.V.M30.X.I.U2.2300.Z01.A"),),
          group="Kredit og penge"),
    Panel("ecb_balance", "europe", "ECB's balance", "mio. EUR",
          "Eurosystemets samlede aktiver (ugentligt). Faldende balance = QT (opstramning).",
          (S("ecb_assets", "Samlede aktiver", "fred", "ECBASSETSW"),), change="pct",
          group="Kredit og penge"),
    Panel("eu_credit", "europe", "Euro high yield-spread", "%-point",
          "Merrente på risikable europæiske virksomhedsobligationer.",
          (S("eu_hy", "Euro high yield", "fred", "BAMLHE00EHYIOAS"),),
          group="Kredit og penge"),
    Panel("eurusd", "europe", "EUR/USD", "USD pr. EUR",
          "Eurokursen over for dollar (ECB's referencekurs).",
          (S("eurusd", "EUR/USD", "ecb", "EXR/D.USD.EUR.SP00.A"),), change="pct", decimals=4,
          group="Valuta"),
    Panel("eur_gbp_chf", "europe", "EUR/GBP og EUR/CHF", "pr. EUR",
          "Euroen over for pund og schweizerfranc (ECB's referencekurser).",
          (S("eurgbp", "EUR/GBP", "ecb", "EXR/D.GBP.EUR.SP00.A"),
           S("eurchf", "EUR/CHF", "ecb", "EXR/D.CHF.EUR.SP00.A")), change="pct", decimals=4,
          group="Valuta"),
    Panel("uk", "europe", "UK: renter og inflation", "%",
          "Bank of Englands styringsrente, 10-årig statsrente og britisk CPI-inflation.",
          (S("uk_bank_rate", "BoE-rente", "bis", "D.GB"),
           S("gb_10y", "10-årig statsrente", "oecd_lt", "GBR"),
           S("uk_cpi", "CPI (% år/år)", "imf_cpi", "GBR")),
          group="Storbritannien"),

    # ----------------------------------------------------------------- DANMARK
    Panel("dk_rates", "denmark", "Nationalbankens renter", "%",
          "Nationalbanken følger ECB for at holde fastkursen. DESTR er den danske dag-til-dag-rente.",
          (S("dk_cd", "Indskudsbevisrente", "statbank", "DNRENTD?INSTRUMENT=OIBNAA&LAND=DK&OPGOER=E"),
           S("dk_current", "Foliorente", "statbank", "DNRENTD?INSTRUMENT=OFONAA&LAND=DK&OPGOER=E"),
           S("dk_lending", "Udlånsrente", "statbank", "DNRENTD?INSTRUMENT=OIRNAA&LAND=DK&OPGOER=E"),
           S("destr", "DESTR", "statbank", "DNRENTD?INSTRUMENT=DESNAA&LAND=DK&OPGOER=E"))),
    Panel("dk_ecb_spread", "denmark", "Rentespænd til ECB", "%-point",
          "Nationalbankens indskudsbevisrente minus ECB's indlånsrente. Bruges til at forsvare kronen.",
          (S("dk_ecb", "Danmark − ECB", "derived", ("dk_cd", "ecb_dfr"), "spread"),)),
    Panel("eurdkk", "denmark", "EUR/DKK (fastkurs)", "DKK pr. EUR",
          "Kronen er bundet til euroen omkring centralkursen 7,46038.",
          (S("eurdkk", "EUR/DKK", "ecb", "EXR/D.DKK.EUR.SP00.A"),), change="pct", decimals=4,
          reference_lines=((7.46038, "Centralkurs 7,46038"),)),
    Panel("dk_10y", "denmark", "10-årig statsrente", "%",
          "Dansk 10-årig statsrente sammenlignet med Tyskland.",
          (S("dk_10y", "Danmark", "oecd_lt", "DNK"),
           S("dk_de_10y", "Spænd til Tyskland", "derived", ("dk_10y", "de_10y"), "spread"))),
    Panel("dk_mortgage", "denmark", "Realkreditrente (nye lån)", "%",
          "Gennemsnitlig rente inkl. bidrag på nye realkreditlån til husholdninger.",
          (S("dk_mort", "Nye lån, husholdninger", "statbank",
             "DNRNURI?DATA=AL51EFFR&INDSEK=1400&VALUTA=Z01&LØBETID1=ALLE&RENTFIX=ALLE&LAANSTR=ALLE"),)),
    Panel("dk_inflation", "denmark", "Inflation (forbrugerpriser)", "% år/år",
          "Ændring i forbrugerprisindekset sammenlignet med samme måned året før.",
          (S("dk_cpi", "Forbrugerprisindeks", "statbank", "PRIS01?VAREGR=000000&ENHED=300"),),
          # Denmark has no target of its own; the fixed exchange rate imports the ECB's.
          reference_lines=INFLATION_TARGET_ECB),
    Panel("dk_unemployment", "denmark", "Ledighed", "% af arbejdsstyrken",
          "Sæsonkorrigeret bruttoledighed.",
          (S("dk_unrate", "Ledighed", "statbank", "AUS08?OMRÅDE=000&SAESONFAK=9"),)),
    Panel("dk_gdp", "denmark", "BNP-vækst", "% k/k",
          "Real, sæsonkorrigeret BNP-vækst i forhold til kvartalet før.",
          (S("dk_gdp", "Real BNP", "statbank", "NKN1?TRANSAKT=B1GQK&PRISENHED=L_V&SÆSON=Y"),)),
    Panel("dk_housing", "denmark", "Huspriser", "% år/år",
          "Prisudvikling på ejendomssalg i hele landet.",
          (S("dk_house", "Enfamiliehuse", "statbank", "EJ56?OMRÅDE=000&EJENDOMSKATE=0111&TAL=310"),
           S("dk_flat", "Ejerlejligheder", "statbank", "EJ56?OMRÅDE=000&EJENDOMSKATE=2103&TAL=310"))),
    Panel("dk_confidence", "denmark", "Forbrugertillid", "Nettotal",
          "Forbrugernes forventninger til egen og landets økonomi. Over 0 = optimisme.",
          (S("dk_ftillid", "Forbrugertillid", "statbank", "FORV1?INDIKATOR=F1"),)),

    # ------------------------------------------------------------------- ASIEN
    # Asian economies without a tab of their own (China, Japan and Korea have one).
    Panel("asia_policy", "asia", "Styringsrenter", "%",
          "Centralbankrenter i Indien, Indonesien og Thailand. Vietnam findes ikke i BIS' data.",
          (S("in_policy", "Indien (RBI)", "bis", "D.IN"),
           S("id_policy", "Indonesien (BI)", "bis", "D.ID"),
           S("th_policy", "Thailand (BoT)", "bis", "D.TH"))),
    Panel("asia_inflation", "asia", "Inflation", "% år/år",
          "Forbrugerprisinflation (IMF).",
          (S("in_cpi", "Indien", "imf_cpi", "IND"),
           S("id_cpi", "Indonesien", "imf_cpi", "IDN"),
           S("th_cpi", "Thailand", "imf_cpi", "THA"),
           S("vn_cpi", "Vietnam", "imf_cpi", "VNM"))),
    Panel("asia_gdp", "asia", "BNP-vækst inkl. IMF-prognose", "% år/år",
          "Real BNP-vækst. Indeværende og kommende år er IMF-prognoser.",
          (S("in_gdp", "Indien", "imf_weo", "NGDP_RPCH/IND"),
           S("id_gdp", "Indonesien", "imf_weo", "NGDP_RPCH/IDN"),
           S("th_gdp", "Thailand", "imf_weo", "NGDP_RPCH/THA"),
           S("vn_gdp", "Vietnam", "imf_weo", "NGDP_RPCH/VNM"))),
    Panel("asia_10y", "asia", "10-årig statsrente: Indien", "%",
          "Månedligt gennemsnit. OECD har ikke tal for Indonesien, Thailand eller Vietnam.",
          (S("in_10y", "Indien", "oecd_lt", "IND"),)),
    Panel("asia_fx", "asia", "USD/INR og USD/THB", "Lokal valuta pr. USD",
          "Indiske rupees og thailandske baht over for dollar. Rupiah og dong findes ikke hos FRED.",
          (S("usdinr", "USD/INR", "fred", "DEXINUS"),
           S("usdthb", "USD/THB", "fred", "DEXTHUS")), change="pct"),

    # -------------------------------------------------------------------- KINA
    Panel("cn_lpr", "china", "Loan Prime Rate (1 år)", "%",
          "Kinas reelle styringsrente siden 2019 (benchmark for bankernes udlån).",
          (S("cn_lpr", "LPR 1 år", "bis", "D.CN"),)),
    Panel("cn_10y", "china", "10-årig statsrente", "%",
          "Kinesisk 10-årig statsrente sammenlignet med USA.",
          (S("cn_10y", "Kina", "oecd_lt", "CHN"),
           S("us_10y_m", "USA", "fred", "GS10"))),
    Panel("cn_inflation", "china", "Inflation", "% år/år",
          "Forbrugerprisinflation. Lav/negativ inflation har været et tegn på svag efterspørgsel.",
          (S("cn_cpi", "CPI", "imf_cpi", "CHN"),)),
    Panel("usdcny", "china", "USD/CNY", "CNY pr. USD",
          "Yuan over for dollar. Styres delvist af centralbanken.",
          (S("usdcny", "USD/CNY", "fred", "DEXCHUS"),), change="pct", decimals=4),
    Panel("cn_gdp", "china", "BNP-vækst inkl. IMF-prognose", "% år/år",
          "Real BNP-vækst. Indeværende og kommende år er IMF-prognoser.",
          (S("cn_gdp", "Kina", "imf_weo", "NGDP_RPCH/CHN"),)),
    Panel("cn_debt", "china", "Statsgæld", "% af BNP",
          "Bruttogæld i den offentlige sektor (IMF; indeværende og kommende år er prognoser).",
          (S("cn_debt", "Offentlig gæld", "imf_weo", "GGXWDG_NGDP/CHN"),)),
    Panel("cn_current_account", "china", "Betalingsbalance", "% af BNP",
          "Overskud på betalingsbalancens løbende poster (IMF; indeværende og kommende år er prognoser).",
          (S("cn_ca", "Løbende poster", "imf_weo", "BCA_NGDPD/CHN"),)),

    # ------------------------------------------------------------------- JAPAN
    Panel("jp_policy", "japan", "BoJ-rente og pengemarked", "%",
          "Bank of Japans styringsrente og den 3-måneders interbankrente (månedlig).",
          (S("jp_policy", "BoJ-rente", "bis", "D.JP"),
           S("jp_3m", "3-mdr. interbankrente", "fred", "IR3TIB01JPM156N")),
          group="Renter"),
    Panel("jp_jgb", "japan", "Statsrenter (JGB)", "%",
          "Japanske statsrenter fra finansministeriets daglige rentekurve.",
          (S("jgb_10y", "10 år", "mof", "10Y"),
           S("jgb_2y", "2 år", "mof", "2Y"),
           S("jgb_5y", "5 år", "mof", "5Y"),
           S("jgb_30y", "30 år", "mof", "30Y")),
          group="Renter"),
    Panel("jp_curve", "japan", "JGB-rentekurve-spread", "%-point",
          "10-årig minus 2-årig statsrente. Stigende spread: markedet venter højere renter på lang sigt.",
          (S("jgb_10y2y", "10 år − 2 år", "derived", ("jgb_10y", "jgb_2y"), "spread"),),
          group="Renter"),
    Panel("jp_inflation", "japan", "Inflation", "% år/år",
          "Forbrugerprisinflation (IMF). Kerneinflation findes ikke i de gratis kilder, vi bruger.",
          (S("jp_cpi", "CPI", "imf_cpi", "JPN"),),
          group="Økonomi", reference_lines=((2.0, "BoJ-mål 2 %"),)),
    Panel("jp_unemployment", "japan", "Ledighed", "%",
          "Harmoniseret arbejdsløshed (OECD), sæsonkorrigeret.",
          (S("jp_unrate", "Ledighed", "fred", "LRHUTTTTJPM156S"),),
          group="Økonomi"),
    Panel("jp_gdp_q", "japan", "BNP-vækst (kvartal)", "% år/år",
          "Real BNP sammenlignet med samme kvartal året før.",
          (S("jp_gdp_q", "Real BNP", "fred", "NGDPRSAXDCJPQ", "yoy"),),
          group="Økonomi"),
    Panel("jp_gdp", "japan", "BNP-vækst inkl. IMF-prognose", "% år/år",
          "Real BNP-vækst pr. år. Indeværende og kommende år er IMF-prognoser.",
          (S("jp_gdp", "Japan", "imf_weo", "NGDP_RPCH/JPN"),),
          group="Økonomi"),
    Panel("jp_exports", "japan", "Eksport", "% år/år",
          "Vareeksportens værdi i yen sammenlignet med samme måned året før (OECD).",
          (S("jp_exports", "Vareeksport", "fred", "XTEXVA01JPM664S", "yoy"),),
          group="Økonomi"),
    Panel("usdjpy", "japan", "USD/JPY", "JPY pr. USD",
          "Yenen over for dollar. Påvirkes stærkt af renteforskellen mellem USA og Japan.",
          (S("usdjpy", "USD/JPY", "fred", "DEXJPUS"),), change="pct",
          group="Markeder og gæld"),
    Panel("nikkei", "japan", "Nikkei 225", "Indeks",
          "Japans førende aktieindeks (prisindeks).",
          (S("nikkei", "Nikkei 225", "fred", "NIKKEI225"),), change="pct",
          group="Markeder og gæld"),
    Panel("jp_debt", "japan", "Statsgæld", "% af BNP",
          "Offentlig bruttogæld (IMF; indeværende og kommende år er prognoser).",
          (S("jp_debt", "Offentlig gæld", "imf_weo", "GGXWDG_NGDP/JPN"),),
          group="Markeder og gæld"),

    # ---------------------------------------------------------------- SYDKOREA
    Panel("kr_policy", "korea", "BoK-rente og pengemarked", "%",
          "Bank of Koreas styringsrente og den 3-måneders interbankrente (månedlig).",
          (S("kr_policy", "BoK-rente", "bis", "D.KR"),
           S("kr_3m", "3-mdr. interbankrente", "fred", "IR3TIB01KRM156N")),
          group="Renter"),
    Panel("kr_10y", "korea", "10-årig statsrente og spænd til USA", "%",
          "Koreansk 10-årig statsrente (månedligt gennemsnit) og forskellen til den amerikanske.",
          (S("kr_10y", "Sydkorea", "oecd_lt", "KOR"),
           S("kr_us_10y", "Spænd til USA", "derived", ("kr_10y", "us_10y_m"), "spread")),
          group="Renter"),
    Panel("kr_inflation", "korea", "Inflation", "% år/år",
          "Forbrugerprisinflation (IMF).",
          (S("kr_cpi", "CPI", "imf_cpi", "KOR"),),
          group="Økonomi", reference_lines=((2.0, "BoK-mål 2 %"),)),
    Panel("kr_unemployment", "korea", "Ledighed", "%",
          "Harmoniseret arbejdsløshed (OECD), sæsonkorrigeret.",
          (S("kr_unrate", "Ledighed", "fred", "LRHUTTTTKRM156S"),),
          group="Økonomi"),
    Panel("kr_gdp_q", "korea", "BNP-vækst (kvartal)", "% år/år",
          "Real BNP sammenlignet med samme kvartal året før.",
          (S("kr_gdp_q", "Real BNP", "fred", "NGDPRSAXDCKRQ", "yoy"),),
          group="Økonomi"),
    Panel("kr_gdp", "korea", "BNP-vækst inkl. IMF-prognose", "% år/år",
          "Real BNP-vækst pr. år. Indeværende og kommende år er IMF-prognoser.",
          (S("kr_gdp", "Sydkorea", "imf_weo", "NGDP_RPCH/KOR"),),
          group="Økonomi"),
    Panel("kr_exports", "korea", "Eksport", "% år/år",
          "Vareeksportens værdi i won sammenlignet med samme måned året før (OECD). "
          "Koreas eksport af chips og elektronik følges som en tidlig indikator for den globale cyklus.",
          (S("kr_exports", "Vareeksport", "fred", "XTEXVA01KRM664S", "yoy"),),
          group="Økonomi"),
    Panel("usdkrw", "korea", "USD/KRW", "KRW pr. USD",
          "Won over for dollar.",
          (S("usdkrw", "USD/KRW", "fred", "DEXKOUS"),), change="pct",
          group="Markeder og gæld"),
    Panel("kr_household_debt", "korea", "Husholdningsgæld", "% af BNP",
          "Husholdningernes samlede gæld (BIS, kvartalsvis). Nr. 9 af 48 lande i BIS' data (1. kvt. 2026).",
          (S("kr_hh_debt", "Husholdninger", "bis", "WS_TC/Q.KR.H.A.M.770.A"),),
          group="Markeder og gæld"),
    Panel("kr_debt", "korea", "Statsgæld", "% af BNP",
          "Offentlig bruttogæld (IMF; indeværende og kommende år er prognoser).",
          (S("kr_debt", "Offentlig gæld", "imf_weo", "GGXWDG_NGDP/KOR"),),
          group="Markeder og gæld"),
]
